linuxmint/cinnamon-spices-desklets

analog-clock@cobinja.de/files/analog-clock@cobinja.de/desklet.js

Bottom and right margins were not used on startup, only after size change.
Also switched from St.Group to St.Widget.

[analog-clock@cobinja.de] Fix margin on startup

---

analog-clock@cobinja.de/files/analog-clock@cobinja.de/3.0/settings.py

This makes sure that python 3.x and gtk 3.x are used for the settings dialog

[analog-clock@cobinja.de] Move settings dialog to python3 and Gtk3

---

clock@schorschii/files/clock@schorschii/desklet.js

When not smoothing the seconds, having the desklet refresh every 1000 ms can lead to a situation where the second consistently updates 999ms into the second, so the clock appears to be nearly 1s slow. This patch causes the next refresh to be immediately after the next change of second.

Refresh when second next changes

---

clock@schorschii/files/clock@schorschii/desklet.js
clock@schorschii/files/clock@schorschii/po/clock@schorschii.pot
clock@schorschii/files/clock@schorschii/po/de.po
clock@schorschii/files/clock@schorschii/po/zh_CN.po
clock@schorschii/files/clock@schorschii/settings-schema.json

The hour hand of an analogue clock should always indicate partial elapsed hours, even when seconds and minutes are not 'smoothed'. At 9:55 the hour hand should not point at 270° straight to the nine. We are so used to this that if it is not smoothed then close to the hour it easy to glance at the clock and see it as 8:55. I've checked all the clocks I can find, both real and virtual. Smoothing the hour is always done. 
I've left the minute as this is less universal. Some do, some don't. I think I prefer not, but I'm not sure. Perhaps smoothing minutes should be an additional configuration option?
@schorschii

clock@schorschii: Always smooth hour hand

---

TimeAndDate@nightflame/info.json
WeatherUnderground@nightflame/info.json
binaryclockdesklet@entelechy/info.json

These desklets are abandoned and the authors never responded and have no activity on GitHub in the last few years. So move authors to `original_author` and set author to `none`
@entelechy
@nightflame

3 applets: set author to none for abandoned desklets

---

ganjine@mohammad-sn/README.md

Replaced relative links to desklet icon and configuration screenshot by absolute githubusercontent links to show correctly on spices website.

Ganjine: update readme file

---

analog-clock@cobinja.de/files/analog-clock@cobinja.de/themes/Blue light basic/metadata.json

The timezone label was not displayed inside the clock.

[analog-clock@cobinja.de] Fix timezone label in Blue light basic theme

---

googleCalendar@javahelps.com/README.md
googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/desklet.js

This PR contains fixes for:
- transparency slider working in opposite direction
- `gcalcli` command to update initialize the account
- settings.bind method according to Cinnamon 3.2+.
Please review and merge the changes.
Thanks

googleCalendar@javahelps.com: Fix transparency settings

---

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/desklet.js
googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/po/de.po
googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/po/googleCalendar.pot

... and German translation
@slgobinath fyi
If Strings in the desklet.js file need to be translated, you need to put them in brackets with an underscore, i.e. like this `_("")`
The translation template file (important for translators) is `po/googleCalendar.pot`. If you add/change translatable strings, you don't need to update the translation files `.po`, but you need only to update the template `.pot` file with the following command:
```
cd ~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com
cinnamon-json-makepot --js po/googleCalendar.pot
```

googleCalendar@javahelps.com: add translation support

---

bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/desklet.js
bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/help.html
bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/settings-schema.json

OpenWeatherMap's [API](https://openweathermap.org/api) differs with a free account ([5 day / 3 hour forecast](https://openweathermap.org/forecast5) or [16 day / daily forecast](https://openweathermap.org/forecast16))
This commit allow users to use the 5 day forecast API (the only one available with free accounts).

Add support for OpenWeatherMap with a free account

---

bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/desklet.js
bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/help.html

This commit addresses a regression introduced in pull request #215 which broke the use of latitude / longitude for specifying location in the original OWM driver. It also makes a number of tweaks to the new driver, addressing some of the issues identified in comments on request #215. Finally, it makes an effort to guess at the time zone for the forecast location so that individual three hourly forecasts are included in the correct day, relative the forecast location.

Tweaks and changes to new Open Weather Map Free driver

---

bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/desklet.js

Ensure that we don't use an undefined value from the _geocache (it was throwing the occasional warning in lookingglass)

bbcwx@oak-wood.co.uk: Minor bug fix

---

googleCalendar@javahelps.com/README.md
googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/metadata.json

Issue related: https://github.com/linuxmint/cinnamon-spices-desklets/issues/265

googleCalendar@javahelps.com: Set compatible cinnamon versions

---

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/settings-schema.json

This PR fixes config dialog not opening in Linux Mint 19 for Google Calendar desklet.
@jaszhix please check this PR.
Thanks

googleCalendar@javahelps.com: Fix config dialog not opening

---

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/desklet.js

`gcalcli` v4.0.0a3 (available on LM 19) expects arguments in a strict order which does not allow current desklet to change Calendar names.
This PR fixes the argument order. New arguments order is checked with both v4.0.0a3 and v3.3.2 (available on LM 18)
@jaszhix please check this PR.
Thanks

Fix gcalcli 4 argument order mismatch

---

analog-clock@cobinja.de/files/analog-clock@cobinja.de/2.8/desklet.js

Passing context to the SignalManager constructor creates circular references, which makes memory management more complicated for the JS engine.
This is a fix for https://github.com/linuxmint/Cinnamon/pull/7868.
@Cobinja

analog-clock@cobinja.de: Avoid passing context to SignalManager

---

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/desklet.js
googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/lib/utility.js
googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/lib/xdate.js

Hi,
The following error messages appeared in `.xsession-errors`:
```
Cjs-Message: 09:14:55.905: JS WARNING: [/home/claude/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/xdate.js 13]: test for equality (==) mistyped as assignment (=)?
(cinnamon:2143): Cjs-WARNING **: 09:14:55.923: Some code accessed the property 'XDate' on the module 'utility'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
(cinnamon:2143): Cjs-WARNING **: 09:14:55.923: Some code accessed the property 'SpawnReader' on the module 'utility'. That …
```

googleCalendar@javahelps.com - Fixes some bugs that sent a lot of messages in .xsession-errors

---

netusage@30yavash.com/files/netusage@30yavash.com/4.0/desklet.js
netusage@30yavash.com/files/netusage@30yavash.com/desklet.js
netusage@30yavash.com/files/netusage@30yavash.com/metadata.json

Significant change to code to identify device as old code failed under Cinnamon 4.0
* New code is identical to that used in applets vnstat@linuxmint.com and 
* Has been in use since Cinnamon 1.8 in netusagemonitor@pdcurtis
Has been tested in netusage@30yavash.com  under:
*  Mint 19 with Cinnamon 3.8.9
* Mint 19.1 Beta with Cinnamon 4.03 on a LiveUSB

netusage@30yavash.com - Replace code which fails to identify active device under Cinnamon 4.0

---

simple-system-monitor@ariel/files/simple-system-monitor@ariel/4.0/desklet.js
simple-system-monitor@ariel/files/simple-system-monitor@ariel/4.0/stylesheet.css
simple-system-monitor@ariel/files/simple-system-monitor@ariel/metadata.json

Updates for Cinnamon 4.0 to avoid segfaults when old Network Manager Library is no longer available by using a multiversion with a folder 4.0 with changes to:
* Comment out or delete all references to NetworkManager
* Replace calls to NetworkManager with equivalent calls to NM
* Change logError messages to remove references to NetworkManager 
This has been tested under a LiveUSB with Mint 19.1 and Cinnamon 4.03
Fixes #279

simple-system-monitor@ariel update to support  Network Manager changes in Cinnamon 4.0

---

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/py/google_calendar.py

@slgobinath 
Fixes `ValueError: astimezone() cannot be applied to a naive datetime` in older versions of `python3`.
Closes #387.

googleCalendar@javahelps.com: localize time (python 3.5)

---

bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/po/it.po

Fixed a small typo in the Italian localization

bbcwx@oak-wood.co.uk: Fix typo in Bold city name

---

clockTow@armandobs14/files/clockTow@armandobs14/desklet.js
clockTow@armandobs14/files/clockTow@armandobs14/metadata.json

I suggest using the date format and language depending on the user's locale (LANG env variable).
How it will be: 
arabic
english (us)
japanese
etc.

clockTow@armandobs14: date format in user language

---

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/lib/xdate.js

Hi @slgobinath,
I propose two minor changes in `lib/xdate.js` to avoid noisy messages in `~/.xsession-errors`.
Tested for a few days, your fabulous desklet still works very well with these changes.
Kind regards.
Claudiux

[googleCalendar@javahelps.com] Updated xdate.js: avoid error messages in ~/.xsession-errors

---

googleCalendar@javahelps.com/README.md

This PR adds link to my post on how to setup Google Calendar desklet using users' own OAuth credentials.
@brownsr please check this PR.
Thanks

[googleCalendar@javahelps.com] Add link to how to setup guide

---

system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/desklet.js

Updates:
Used RAM is computed as Total - Available (from `/proc/meminfo`). Values are presented in GiB.
Used space in HDD is computed as Size - Available (from `df` command). Values are presented in GB.
Both RAM and HDD values match the reported in gnome system monitor.

Updates RAM and HDD calculations

---

googleCalendar@javahelps.com/README.md

Add installation command for Arch users and fix an issue with the link for gcalendar.
However the main reason for this PR is triggering an update for Cinnamon Spices rebuild. After merging the last PR, Google Calendar desklet wasn't updated.
@brownsr please check this PR
Thanks

[googleCalendar@javahelps.com] Add Arch installation command and fix a URL

---

clock@schorschii/files/clock@schorschii/settings-schema.json

It turned out that the smooth seconds hand feature is CPU intensive, especially on less powerful CPUs. That's why it should be turned off by default.

clock@schorschii: hide seconds hand by default

---

bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/desklet.js

@tipichris 
During and after updating weather data the TCP state is ESTABLISHED, after a few seconds it changes to CLOSE_WAIT. So far ok, but it stays there "forever".
This pull request fixes this, because connection is closed after 10 seconds now.
Original fix by Gr3q (weather@mockturtl)

bbcwx@oak-wood.co.uk: close session after 10 seconds

---

system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/desklet.js
system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/metadata.json
system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/settings-schema.json

This pull request does the following for the **system-monitor-graph@rcassani** Desklet
- Fix the position of the labels for the CPU, RAM and HDD graphs.
- Allow the use of custom label for the HDD graphs
- Update versioning from 1.0 to 1.1

Fixing labels

---

diskspace@schorschii/files/diskspace@schorschii/desklet.js
diskspace@schorschii/files/diskspace@schorschii/metadata.json
diskspace@schorschii/files/diskspace@schorschii/po/de.po
diskspace@schorschii/files/diskspace@schorschii/po/diskspace@schorschii.pot
diskspace@schorschii/files/diskspace@schorschii/settings-schema.json

This PR adds an option to the diskspace desklet to choose if sizes should be shown decimal or binary, just like in the Nemo file manager settings.

diskspace@schorschii: option to choose decimal/binary prefix

---

analog-clock@cobinja.de/files/analog-clock@cobinja.de/3.0/desklet.js
analog-clock@cobinja.de/files/analog-clock@cobinja.de/3.0/settings.py

This fixes settings dialog startup that failed due to Mint 20 not having an executable called "python" anymore

Fix settings dialog not starting on Mint 20

---

system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/desklet.js
system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/metadata.json
system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/settings-schema.json

- Adds the capacity to monitor Usage and Memory in NVIDIA GPUs.
- User indicates the `Id` of the GPU to monitor. Thus, multiple GPUs can be monitored simultaneously.  
- NVIDIA drivers are needed a the information is obtained with the `nvidia-smi` command.
- Place holders are placed in the JS code for further development to support GPUs from other manufacturers.

Add capacity to monitor Usage and Memory in NVIDIA GPUs

---

ganjine@mohammad-sn/files/ganjine@mohammad-sn/desklet.js

Desklet was failing to install correctly. Replacing "contains" with "includes" fixes the issue and the desklet is working as expected.
@mohammad-sn

Replaces 'contains' with 'includes'.

---

cpuload@kimse/files/cpuload@kimse/desklet.js
cpuload@kimse/files/cpuload@kimse/metadata.json
cpuload@kimse/files/cpuload@kimse/po/cpuload@kimse.pot
cpuload@kimse/files/cpuload@kimse/po/de.po
cpuload@kimse/files/cpuload@kimse/settings-schema.json
cpuload@kimse/files/cpuload@kimse/stylesheet.css

Hi @ipimpat 
I'm using the cpuload and diskspace desklet, which gave me the following ideas to improve the UX for people using both. Hope you like it.
- I propose to change the circle to a "speedometer-like" design. The speedometer design is more common for CPU usage visualization and users can differentiate it from the diskspace desklet on the first sight.
- I propose to adjust the default size to match the default diskspace desklet size.
- I added the new compact design known from the diskspace desklet.

Proposals for cpuload@kimse

---

cpuload@kimse/files/cpuload@kimse/desklet.js
cpuload@kimse/files/cpuload@kimse/settings-schema.json

A user requested an option to change the font color, so I added that, because it was simple to implement.
Also would it be better, to call the option "Text color" instead of "Font color" ?
@schorschii care to comment :-) ?

Added font color chooser option to the cpuload@kimse desklet

---

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/lib/utility.js
googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/writeEvents.sh

Hopefully `Util.spawnCommandLineAsyncIO` won't cause the `GLib.Error g-unix-error-quark: Too many open files` error.

Spawn gcalendar using Util.spawnCommandLineAsyncIO function

---

notes@schorschii/files/notes@schorschii/desklet.js

Reloading of the note file every 2 secs, possibly causing periodical "stuttering" of the desktop, replaced by monitoring of its changes.

 notes@schorschii desklet: file monitor instead of file reloading every 2s

---

bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/desklet.js

Several of the weather API data sources in bbcwx@oak-wood.co.uk use HTTP for connections when HTTPS (TLS) connections are available. This is negative because it enhances the ability to track users who utilize this desklet. 
Changing these URLs from HTTP:// to HTTPS:// will resolve this issue.
I went through and changed the URLs and verified the back end services support HTTP, there should be no impact, it is working and connecting over HTTPS as expected on Debian unstable. 
This mitigates tracking of users (leakage of globally unique API keys in plaintext on an interval)

bbcwx@oak-wood.co.uk: Convert HTTP services to HTTPs

---

notes@schorschii/files/notes@schorschii/desklet.js
notes@schorschii/files/notes@schorschii/settings-schema.json

This commit provides a settings option to set a custom background color when the note style is set to "None". The default background color is transparent, so that the desklet behaves like before if a user does not want to make use of the option.
@schorschii

notes@schorscii: Add option to set custom background color

---

system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/desklet.js
system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/metadata.json

It fixes as perceptible pause when the GPU readings were used. 
This PR updates the desklet to use `wait_asynch` to wait for getting the different measurements (CPU, RAM, HDD, and GPU). The code refactoring  was inspired by the [diskspace@schorschii](https://github.com/linuxmint/cinnamon-spices-desklets/tree/master/diskspace%40schorschii/files/diskspace%40schorschii) desklet.
I have tested all the measurements except for `Swap`, as I don't have access to a system with swap partition. It would be good to test this before merging.

system-monitor-graph@rcassani - Use asynchronous wait when taking measurements

---

xkcd@rjanja/files/xkcd@rjanja/desklet.js
xkcd@rjanja/files/xkcd@rjanja/metadata.json

@rjanja
The default savepath for images is `~/Pictures`. If your system was setup in another language, this folder may not exist, for example it's `~/Images` instead, in french.
With this PR, the default value for metadata.directory is now `"<DIRECTORY_PICTURES>/xkcd"`, which will find the right default picture folder on the system.
Possible values are the list of special directories found here https://gjs-docs.gnome.org/glib20~2.66.1/glib.userdirectory
Nb:
- Special directory is optional. `~/xkdc` or `Pictures/xkcd` will still work.
- Program looks for special name within `<...>` at the start of the path. 
- To use special name, path must start with it (`/home/<DIRECTORY_PICTURES>/xkcd` is not valid ; `<DIRECTORY_PICTURES>/xkcd` is valid)
- Invalid special name will be replaced by the …

xkcd@rjanja: Added support for localized special directories name 

---

bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/desklet.js
bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/po/bbcwx@oak-wood.co.uk.pot
bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/po/de.po
bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/settings-schema.json

This commit provides a settings option to set a text shadow with customizable blur-radius to implement a better contrast in conjunction with low background opacity.
closes #758

bbcwx@oak-wood.co.uk: Add option to set custom text shadow

---

quoteOfTheDay@tinnu/files/quoteOfTheDay@tinnu/3.2/desklet.js
quoteOfTheDay@tinnu/files/quoteOfTheDay@tinnu/3.6/desklet.js
quoteOfTheDay@tinnu/files/quoteOfTheDay@tinnu/desklet.js

This PR fixes #825.
The parameters entered get split on spaces, and the resulting array is then merged with the other `argv` arguments (by using the spread operator).
The only downside of this is that regular expressions (using the `-m pattern` option) cannot include spaces. If there are any other ideas on how to split the parameter list please let me know.

[quoteOfTheDay@tinnu] Allow usage of multiple parameters for fortune command

---

xkcd@rjanja/files/xkcd@rjanja/desklet.js

The desklet is broken on mint 21 due to newer version of CJS:
* newest Clutter version removed `Clutter.Texture` : Replaced `Clutter.Texture` by `Clutter.Image` (for display the comic) + `GdkPixbuf` for loading image from file.
* newest Soup version removed `Cinnamon.write_soup_message_to_stream(...)` : fixed using `stream.write_bytes()`
Also removed useless and now broken tooltip part
Also fixed warning about `Mainloop.source_remove()` that showed up in Cinnamon log due to `this._timeoutId` not being unset.
Nb: I couldn't find which versions are used by CJS exactly. Looks like Soup 2.4 and Clutter above 7.
Nb 2 : Clutter project is now EOL (https://blogs.gnome.org/clutter/) so eventually it will have to be replaced.
Tested under Mint 20 and 21

[xkcd@rjanja] Fix for mint 21

---

notes@schorschii/files/notes@schorschii/desklet.js

This fix avoids Array.toString() warning messages appearing in ~/.xsession-errors, like:
```
(cinnamon:2062): Gjs-WARNING **: 23:25:36.963: Some code called array.toString() on a Uint8Array instance. Previously this would have interpreted the bytes of the array as a string, but that is nonstandard. In the future this will return the bytes as comma-separated digits. For the time being, the old behavior has been preserved, but please fix your code anyway to explicitly call ByteArray.toString(array).
(Note that array.toString() may have been called implicitly.)
```
Thanks to @claudiux for bringing this up.
---
To the Mint maintainer merging this PR: please also have a look at https://github.com/linuxmint/cinnamon-spices-desklets/pull/841 and …

avoid Array.toString() error messages

---

bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/desklet.js

bbcwx@oak-wood.co.uk did not work on Mint 18.3 (Cinnamon 3.6.7), because version of Soup library was incorrectly detected. Bug was found when using data from free openweathermap.com API.
@tipichris

bbcwx@oak-wood.co.uk: Fixed incorrectly detected Soup version

---

InternetTimeDesklet@stefan/files/InternetTimeDesklet@stefan/desklet.js

Change the hour/minute/second variable assignments to explicitly be in UTC format. Also, add one hour to the "getUTCHours()" call, as "Biel Mean Time" (BMT), which Beat Time is based upon, is defined by Swatch as UTC+1.
Previously this was calling Date's getHours/getMinutes/getSeconds function family, which returns _LOCAL_ time. This had the effect of the Beat time returned by this desklet **always** being incorrect unless your computer's time is set to the UTC+1 timezone.
This commit fixes that and ensures that the correct universal Beat Time will be displayed regardless of the user's timezone.
Original author of this desklet is @stefan12O

InternetTimeDesklet@stefan: Fix timezone for accurate Beat Time calculation

---

calculator@scollins/files/calculator@scollins/desklet.js

Some variable declarations/"let" statements appeared to be missing. Refactored the code a bit and avoided missing "let" statements. That should fix #769

calculator@scollins:Fix broken rpn operators/#769

---

system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/desklet.js
system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/metadata.json

Hi @rcassani , we noticed that `subprocess.init(null)` causes microstutters on our desktops, see #932. This PR fixes the issue like in my diskspace desklet (#937).
With this change, the values are read directly from files using Gio's `load_contents_async` instead of spawning `head` or `cat` subprocesses to read it.
For scenarios where this is not possible (NVIDIA GPU monitoring), I switched `subprocess.wait_async` to `load_contents_async` and `load_contents_finish` which seems to be the correct way to read subprocess output async, as described [here in the Gio docs](https://docs.gtk.org/gio/method.Subprocess.communicate_utf8_async.html).

system-monitor-graph@rcassani: Fix Stuttering

---

calendar@schorschii/README.md
calendar@schorschii/files/calendar@schorschii/desklet.js
calendar@schorschii/files/calendar@schorschii/metadata.json
calendar@schorschii/files/calendar@schorschii/po/ca.po
calendar@schorschii/files/calendar@schorschii/po/calendar@schorschii.pot
calendar@schorschii/files/calendar@schorschii/po/da.po
calendar@schorschii/files/calendar@schorschii/po/de.po
calendar@schorschii/files/calendar@schorschii/po/es.po
calendar@schorschii/files/calendar@schorschii/po/hu.po
calendar@schorschii/files/calendar@schorschii/po/it.po
calendar@schorschii/files/calendar@schorschii/po/pt_BR.po
calendar@schorschii/files/calendar@schorschii/po/ro.po
calendar@schorschii/files/calendar@schorschii/po/sk.po
calendar@schorschii/files/calendar@schorschii/po/sv.po
calendar@schorschii/files/calendar@schorschii/po/tr.po
calendar@schorschii/files/calendar@schorschii/po/zh_CN.po
calendar@schorschii/files/calendar@schorschii/settings-schema.json

- replaced synchronous file read with async alternative to avoid warning in the desklet manager
- mentioned .ics as more common file extension besides .ical
- added readme how to configure Thunderbird to write the calendar into an .ics file for use with the desklet

calendar@schorschii improvements

---

diskspace@schorschii/files/diskspace@schorschii/desklet.js
diskspace@schorschii/files/diskspace@schorschii/metadata.json
diskspace@schorschii/files/diskspace@schorschii/po/de.po
diskspace@schorschii/files/diskspace@schorschii/po/diskspace@schorschii.pot
diskspace@schorschii/files/diskspace@schorschii/settings-schema.json

See discussion #940. This adds an option to let the user decide how to display reserved blocks.

diskspace@schorschii: option to display reserved blocks as free space

---

system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/po/de.po
system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/po/system-monitor-graph@rcassani.pot

The .pot file was missing some translations. I added them with the German translations.

system-monitor-graph@rcassani: add missing translations

---

battery@schorschii/files/battery@schorschii/desklet.js
battery@schorschii/files/battery@schorschii/metadata.json
battery@schorschii/files/battery@schorschii/stylesheet.css
calendar@schorschii/files/calendar@schorschii/desklet.js
calendar@schorschii/files/calendar@schorschii/metadata.json
diskspace@schorschii/files/diskspace@schorschii/desklet.js
diskspace@schorschii/files/diskspace@schorschii/metadata.json
diskspace@schorschii/files/diskspace@schorschii/settings-schema.json
hostcheck@schorschii/files/hostcheck@schorschii/desklet.js
hostcheck@schorschii/files/hostcheck@schorschii/metadata.json
hostcheck@schorschii/files/hostcheck@schorschii/settings-schema.json
hostcheck@schorschii/files/hostcheck@schorschii/stylesheet.css

I unified the default width of my desklets to 150px so that they better fit together on the desktop.

@schorschii desklets: unify desklet width

---

hostcheck@schorschii/README.md

`curl` is not necessary anymore in v1.4.
Forgot this small change in #1026 , sorry.

hostcheck@schorschii: Readme update

---

dual-datetime@rcalixte/CHANGELOG.md
dual-datetime@rcalixte/files/dual-datetime@rcalixte/5.4/settings-schema.json
dual-datetime@rcalixte/files/dual-datetime@rcalixte/metadata.json

* Update default time size to 5
* Update default date size to 2.5
* Update default alignments to center for date and time

dual-datetime@rcalixte: Version 1.2.1

---

yfquotes@thegli/README.md
yfquotes@thegli/files/yfquotes@thegli/desklet.js
yfquotes@thegli/files/yfquotes@thegli/metadata.json
yfquotes@thegli/files/yfquotes@thegli/po/da.po
yfquotes@thegli/files/yfquotes@thegli/po/de.po
yfquotes@thegli/files/yfquotes@thegli/po/es.po
yfquotes@thegli/files/yfquotes@thegli/po/fi.po
yfquotes@thegli/files/yfquotes@thegli/po/hu.po
yfquotes@thegli/files/yfquotes@thegli/po/it.po
yfquotes@thegli/files/yfquotes@thegli/po/ko.po
yfquotes@thegli/files/yfquotes@thegli/po/nl.po
yfquotes@thegli/files/yfquotes@thegli/po/pt_BR.po
yfquotes@thegli/files/yfquotes@thegli/po/ro.po
yfquotes@thegli/files/yfquotes@thegli/po/ru.po
yfquotes@thegli/files/yfquotes@thegli/po/yfquotes@thegli.pot
yfquotes@thegli/files/yfquotes@thegli/settings-schema.json

yfquotes@thegli: add setting to manually update quotes data

---

hostcheck@schorschii/files/hostcheck@schorschii/desklet.js

Tested with English and German ping output, both working correctly.

Fix: Support non-English ping output in desklet

---

system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/desklet.js

This pull request fixes the #1100 for the `system-monitor-graph@rcassani` Desklet
I was able to replicate the reported issue, the it was not observed anymore with the proposed changes.
It seems that the order in the `text`, `style` and `positions` are set for `St.Labels` is important. Although I could not find an explanation for this.

Reorder setting label's text, style and position

---

yfquotes@thegli/README.md
yfquotes@thegli/files/yfquotes@thegli/desklet.js
yfquotes@thegli/files/yfquotes@thegli/metadata.json
yfquotes@thegli/files/yfquotes@thegli/po/ca.po
yfquotes@thegli/files/yfquotes@thegli/po/da.po
yfquotes@thegli/files/yfquotes@thegli/po/de.po
yfquotes@thegli/files/yfquotes@thegli/po/es.po
yfquotes@thegli/files/yfquotes@thegli/po/fi.po
yfquotes@thegli/files/yfquotes@thegli/po/hu.po
yfquotes@thegli/files/yfquotes@thegli/po/it.po
yfquotes@thegli/files/yfquotes@thegli/po/ko.po
yfquotes@thegli/files/yfquotes@thegli/po/nl.po
yfquotes@thegli/files/yfquotes@thegli/po/pt_BR.po
yfquotes@thegli/files/yfquotes@thegli/po/ro.po
yfquotes@thegli/files/yfquotes@thegli/po/ru.po
yfquotes@thegli/files/yfquotes@thegli/po/yfquotes@thegli.pot
yfquotes@thegli/files/yfquotes@thegli/settings-schema.json

- implement new feature for individual design of each quote
- changes in quotes list are not instantly applied anymore
- update default value for User-Agent
- correct minor translation flaws
- ignore case on sorting quotes list

yfquotes@thegli: add individual quote design feature

---

notes@schorschii/files/notes@schorschii/desklet.js
notes@schorschii/files/notes@schorschii/metadata.json
notes@schorschii/files/notes@schorschii/po/ca.po
notes@schorschii/files/notes@schorschii/po/da.po
notes@schorschii/files/notes@schorschii/po/de.po
notes@schorschii/files/notes@schorschii/po/es.po
notes@schorschii/files/notes@schorschii/po/fr.po
notes@schorschii/files/notes@schorschii/po/hu.po
notes@schorschii/files/notes@schorschii/po/it.po
notes@schorschii/files/notes@schorschii/po/nl.po
notes@schorschii/files/notes@schorschii/po/notes@schorschii.pot
notes@schorschii/files/notes@schorschii/po/pt.po
notes@schorschii/files/notes@schorschii/po/pt_BR.po
notes@schorschii/files/notes@schorschii/po/ro.po
notes@schorschii/files/notes@schorschii/po/ru.po
notes@schorschii/files/notes@schorschii/po/sv.po
notes@schorschii/files/notes@schorschii/po/tr.po
notes@schorschii/files/notes@schorschii/settings-schema.json

Hello @schorschii,
With this PR I generally made two changes:
1. Reorganize settings, dividing it in two sections **General**, and **Visual**
2. Allow taking notes in the Desklet with the **textview** settings component type. This is a toggeable option, the default is still the text-based note, but you can edit notes directly in the desklet settings now, which makes sense since each Desklet will have its own settings instance.
Example Picture:

notes@schorschii: Allow in desklet note taking

---

notes@schorschii/files/notes@schorschii/po/ca.po
notes@schorschii/files/notes@schorschii/po/da.po
notes@schorschii/files/notes@schorschii/po/de.po
notes@schorschii/files/notes@schorschii/po/es.po
notes@schorschii/files/notes@schorschii/po/fr.po
notes@schorschii/files/notes@schorschii/po/hu.po
notes@schorschii/files/notes@schorschii/po/it.po
notes@schorschii/files/notes@schorschii/po/nl.po
notes@schorschii/files/notes@schorschii/po/notes@schorschii.pot
notes@schorschii/files/notes@schorschii/po/pt.po
notes@schorschii/files/notes@schorschii/po/pt_BR.po
notes@schorschii/files/notes@schorschii/po/ro.po
notes@schorschii/files/notes@schorschii/po/ru.po
notes@schorschii/files/notes@schorschii/po/sv.po
notes@schorschii/files/notes@schorschii/po/tr.po
notes@schorschii/files/notes@schorschii/settings-schema.json

This adds the note that custom labels are only visible when decorations are enabled again after #1293 and updates the German translation.

notes@schorschii: update translations

---

calculator@scollins/files/calculator@scollins/desklet.js

Re-aquire focus on click when in foreground mode, so that typing numbers and closing via ESC is possible again.
Closes #1298

calculator@scollins: re-aquire focus on click when in foreground

---

analog-clock@cobinja.de/files/analog-clock@cobinja.de/po/de.po

Originally, some of the german translations were messed up by https://github.com/linuxmint/cinnamon-spices-desklets/pull/1098/files#diff-61e353a473acee02d5744fe0f681529d71f37e3f63a1e9b3d514a05516e3a454
https://github.com/linuxmint/cinnamon-spices-desklets/pull/1352 fixed those but also changed some that were unchanged by the commit mentioned above.
THis PR reverts those changes.
I personally agree that "Dekorationen" would be more suitable than "Verzierungen". But: Cinnamon Settings -> Desklets -> "Allgemeine Einstellungen" -> "Gestaltung der Desklets" uses the word "Verzierungen" so I used it as well to avoid confusion. The other ones are my personal preference as the original author of this desklet.

[analog-clock@cobinja.de] Fix german translation

---

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/desklet.js
googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/metadata.json
googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/settings-schema.json

@slgobinath
Your fabulous desklet was flooding `~/.xsession-errors` with error messages about `Mainloop.source_remove()`. This PR fixes that.
Also, the maximum “Number of days to include” is now set to 62 (i.e. 2 months)... because I got tired of doing that every time I installed.
I hope you'll like all that.
Regards
Claudiux

[googleCalendar@javahelps.com] Minor bugfixes

---

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/desklet.js

@slgobinath 
These changes avoid errors on Cinnamon 6.4, by avoiding the use of `Mainloop.source_remove()` and adding the _Open Google Calendar_ menu item when it is sure that _this._menu_ exists.

[googleCalendar@javahelps.com] Improved compatibility with Cinnamon 6.4 - Bugfixes

---

system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/desklet.js
system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/metadata.json
system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/settings-schema.json

This commit adds support for showing GPU and VRAM usage on GPUs which make use of the amdgpu driver.
It should be noted that GPU usage can be somewhat inaccurate because of the low sampling frequency.

system-monitor-graph@rcassani: Add support for amdgpu, and bump version

---

system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/desklet.js
system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/metadata.json

Fixes the bug reported in #1396 
The bug was introduced in #1394 as `switch` structures in JavaScript are fall-through. 
https://www.freecodecamp.org/news/fall-through-in-javascript-switch-statements/
So, with `NVIDIA` selected, both cases `nvidia` and `amd` were executed.
The fix just ends each GPU manufacturer case with `break;`
Also
- Updated version number
- Indentation change for clearer code
@Lazar-Kovacevic, the AMD support should be working properly

Bugfix: `switch` structures in JavaScripts are fall-through

---

system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/desklet.js
system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/metadata.json

These commits add error checking to prevent desklet or cinnamon crashes when any of the used files are absent from the system, most often because the system doesn't have a gpu from AMD.
It also switches amdgpu functions to use async function calls for file reading, like the rest of the desklet.
@rcassani Sorry for submitting broken code last time, I did a lot more testing this time and it seems to be ok.

system-monitor-graph@rcassani: Add error handling for amdgpu

---

notes@schorschii/files/notes@schorschii/desklet.js
notes@schorschii/files/notes@schorschii/metadata.json
notes@schorschii/files/notes@schorschii/po/ca.po
notes@schorschii/files/notes@schorschii/po/da.po
notes@schorschii/files/notes@schorschii/po/de.po
notes@schorschii/files/notes@schorschii/po/es.po
notes@schorschii/files/notes@schorschii/po/fi.po
notes@schorschii/files/notes@schorschii/po/fr.po
notes@schorschii/files/notes@schorschii/po/hu.po
notes@schorschii/files/notes@schorschii/po/it.po
notes@schorschii/files/notes@schorschii/po/nl.po
notes@schorschii/files/notes@schorschii/po/notes@schorschii.pot
notes@schorschii/files/notes@schorschii/po/pt.po
notes@schorschii/files/notes@schorschii/po/pt_BR.po
notes@schorschii/files/notes@schorschii/po/ro.po
notes@schorschii/files/notes@schorschii/po/ru.po
notes@schorschii/files/notes@schorschii/po/sv.po
notes@schorschii/files/notes@schorschii/po/tr.po
notes@schorschii/files/notes@schorschii/settings-schema.json

Updates notes@schorschii by @schorschii to add word wrapping.
Attempts to integrate code from https://github.com/aizma/Note-by-schorschii---word-wrap/ into current version of notes.
I opened this issue about the idea then decided to do a PR since i had the files already: https://github.com/linuxmint/cinnamon-spices-desklets/issues/1467
It isn't a perfect solution and I don't really know what I'm doing in javascript, but it does seem to work on my end.

notes@schorschii: added word wrapping to notes

---

systemUptime@KopfDesDaemons/files/systemUptime@KopfDesDaemons/desklet.js
systemUptime@KopfDesDaemons/files/systemUptime@KopfDesDaemons/metadata.json
systemUptime@KopfDesDaemons/files/systemUptime@KopfDesDaemons/po/ca.po
systemUptime@KopfDesDaemons/files/systemUptime@KopfDesDaemons/po/de.po
systemUptime@KopfDesDaemons/files/systemUptime@KopfDesDaemons/po/es.po
systemUptime@KopfDesDaemons/files/systemUptime@KopfDesDaemons/po/hu.po
systemUptime@KopfDesDaemons/files/systemUptime@KopfDesDaemons/po/nl.po
systemUptime@KopfDesDaemons/files/systemUptime@KopfDesDaemons/po/systemUptime@KopfDesDaemons.pot
systemUptime@KopfDesDaemons/files/systemUptime@KopfDesDaemons/settings-schema.json
systemUptime@KopfDesDaemons/info.json

Refers to #1530:
Added the "Show start date" and "Show uptime days" settings.
@schorschii

systemUptime@KopfdesDaemons: add start date, add uptime days

---

system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/desklet.js
system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/metadata.json
system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/po/ca.po
system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/po/da.po
system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/po/de.po
system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/po/es.po
system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/po/fi.po
system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/po/hu.po
system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/po/it.po
system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/po/nl.po
system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/po/pt_BR.po
system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/po/ro.po
system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/po/ru.po
system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/po/system-monitor-graph@rcassani.pot
system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/settings-schema.json

- I think it makes more sense to display network speed as bits/sec rather than bytes/sec, so I added an option for that and made it the default.
- The up/download speed sometimes overlaps, depending on the amount of chars of the current network speed. That's why, I moved this info into the smaller, right-aligned `text3` label.
- Furthermore, I fixed some German translations.
What do you think @rcassani ?

 system-monitor-graph@rcassani: network monitoring adjustments

---

yarr@jtoberling/CHANGELOG.md
yarr@jtoberling/files/yarr@jtoberling/desklet.js
yarr@jtoberling/files/yarr@jtoberling/metadata.json

Quick fix due to CPU usage optimization  - please merge.

yarr/v2.1.1 High CPU% fixup and .xsession-errors pollution
