linuxmint/cinnamon-spices-desklets

clockTow@armandobs14/files/clockTow@armandobs14/desklet.js
This desklet is broken.
As suggested here https://cinnamon-spices.linuxmint.com/desklets/view/6 in the comments by pointer666 comment out line 36 and 37 fixes this desklet
=> [clockTow@armandobs14] fix broken desklet

binaryclock2@euxneks/files/binaryclock2@euxneks/desklet.js, binaryclockdesklet@entelechy/files/binaryclockdesklet@entelechy/desklet.js
The Binary Clock Desklets crashed, when trying to add to Desktop.
This commit fixes the crashes.
=> fix broken binaryclockdesklet@entelechy and binaryclock2@euxneks

battery@schorschii/files/battery@schorschii/desklet.js, battery@schorschii/files/battery@schorschii/metadata.json, battery@schorschii/files/battery@schorschii/settings-schema.json
- code optimizations for battery device file auto detection
=> battery@schorschii: Version 2.1

bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/po/zh_CN.po
=> Add Chinese translation for Weather Desklet

simple-system-monitor@ariel/files/simple-system-monitor@ariel/desklet.js
Issue: Desklet not work if no internet connection at launching PC #10.
Line 111 (now 115) referenced an undeclared variable "ifc".
Another change: If the thermal sensor file is not found, the temperature shown is "N/A" instead of "undefined".
=> Fix for Issue #10

battery@schorschii/files/battery@schorschii/desklet.js, battery@schorschii/files/battery@schorschii/metadata.json, battery@schorschii/files/battery@schorschii/settings-schema.json
- works now with cinnamon versions below 3.2.x
=> battery@schorschii: Version 2.3

analog-clock@cobinja.de/files/analog-clock@cobinja.de/3.0/desklet.js
This removes the config file on desklet removal.
=> [analog-clock@cobinja.de] Clean up after ourselves

simple-system-monitor@ariel/files/simple-system-monitor@ariel/desklet.js, simple-system-monitor@ariel/files/simple-system-monitor@ariel/po/simple-system-monitor@ariel.pot, simple-system-monitor@ariel/files/simple-system-monitor@ariel/po/sv.po
Add l10n translation support, translation template and Swedish translation
=>  	simple-system-monitor@ariel: Add translation

analog-clock@cobinja.de/files/analog-clock@cobinja.de/po/zh_CN.po
=> Add Chinese translation for Analog clock desklet

soundBox@scollins/files/soundBox@scollins/2.5/desklet.js, soundBox@scollins/files/soundBox@scollins/2.8/desklet.js, soundBox@scollins/files/soundBox@scollins/desklet.js, soundBox@scollins/files/soundBox@scollins/po/soundBox@scollins.pot, soundBox@scollins/files/soundBox@scollins/po/zh_CN.po, soundBox@scollins/files/soundBox@scollins/soundbox.js
=> Add translation support for Soundbox

calculator@scollins/files/calculator@scollins/desklet.js, calculator@scollins/files/calculator@scollins/po/calculator@scollins.pot, calculator@scollins/files/calculator@scollins/po/zh_CN.po
=> Add translation support for Desktop Calculator

xkcd@rjanja/files/xkcd@rjanja/desklet.js, xkcd@rjanja/files/xkcd@rjanja/po/xkcd@rjanja.pot, xkcd@rjanja/files/xkcd@rjanja/po/zh_CN.po
=> Add translation support for xkcd comics viewer

temperature@swalladge/files/temperature@swalladge/desklet.js, temperature@swalladge/files/temperature@swalladge/po/temperature@swalladge.pot, temperature@swalladge/files/temperature@swalladge/po/zh_CN.po
=> Add translation support for Temperature

binaryclock2@euxneks/files/binaryclock2@euxneks/po/binaryclock2@euxneks.pot, binaryclock2@euxneks/files/binaryclock2@euxneks/po/zh_CN.po
=> Add translation for Binary Clock²

clock@schorschii/files/clock@schorschii/po/clock@schorschii.pot, clock@schorschii/files/clock@schorschii/po/zh_CN.po
=> Add translation for Analog Chronometer

battery@schorschii/files/battery@schorschii/po/battery@schorschii.pot, battery@schorschii/files/battery@schorschii/po/zh_CN.po
=> Add translation for Battery Level Indicator

powerUsage@hosvir.com/files/powerUsage@hosvir.com/po/powerUsage@hosvir.com.pot, powerUsage@hosvir.com/files/powerUsage@hosvir.com/po/zh_CN.po
=> Add translation support for Power Usage Monitor

reddit-reader@orangeshark/files/reddit-reader@orangeshark/po/reddit-reader@orangeshark.pot, reddit-reader@orangeshark/files/reddit-reader@orangeshark/po/zh_CN.po
=> Add translation for reddit reader desklet

simple-system-monitor@ariel/files/simple-system-monitor@ariel/po/simple-system-monitor@ariel.pot, simple-system-monitor@ariel/files/simple-system-monitor@ariel/po/zh_CN.po
=> Update translation for Simple system monitor

battery@schorschii/files/battery@schorschii/desklet.js, battery@schorschii/files/battery@schorschii/metadata.json, battery@schorschii/files/battery@schorschii/settings-schema.json
- fix capacity indicator when battery reports capacity above 100%
- removed version from settings-schema.json and added to metedata.json
=> battery@schorschii: Version 2.5

powerUsage@hosvir.com/files/powerUsage@hosvir.com/po/de.po
=> powerUsage@hosvir.com: add German translation

binaryclock2@euxneks/files/binaryclock2@euxneks/po/binaryclock2@euxneks.pot, binaryclock2@euxneks/files/binaryclock2@euxneks/po/de.po
=> binaryclock2@euxneks: add German translation & update translation template

simple-system-monitor@ariel/files/simple-system-monitor@ariel/po/de.po, simple-system-monitor@ariel/info.json
=> simple-system-monitor@ariel: fix author name and add German translation

devTools@scollins/files/devTools@scollins/desklet.js, devTools@scollins/files/devTools@scollins/errorLog.js, devTools@scollins/files/devTools@scollins/extensions.js, devTools@scollins/files/devTools@scollins/inspect.js, devTools@scollins/files/devTools@scollins/po/devTools@scollins.pot, devTools@scollins/files/devTools@scollins/po/zh_CN.po, devTools@scollins/files/devTools@scollins/sandbox.js, devTools@scollins/files/devTools@scollins/tab.js, devTools@scollins/files/devTools@scollins/tabPanel.js, devTools@scollins/files/devTools@scollins/terminal.js, devTools@scollins/files/devTools@scollins/windows.js
=> Add translation support for Developer Tools

TimeAndDate@nightflame/files/TimeAndDate@nightflame/desklet.js, TimeAndDate@nightflame/files/TimeAndDate@nightflame/po/TimeAndDate@nightflame.pot, TimeAndDate@nightflame/files/TimeAndDate@nightflame/po/zh_CN.po
=> Add translation support for Time And Date

quoteOfTheDay@tinnu/files/quoteOfTheDay@tinnu/desklet.js, quoteOfTheDay@tinnu/files/quoteOfTheDay@tinnu/po/quoteOfTheDay@tinnu.pot, quoteOfTheDay@tinnu/files/quoteOfTheDay@tinnu/po/zh_CN.po
=> Add translation support for Quote of the day desklet

clockTow@armandobs14/files/clockTow@armandobs14/desklet.js, clockTow@armandobs14/files/clockTow@armandobs14/po/clockTow@armandobs14.pot, clockTow@armandobs14/files/clockTow@armandobs14/po/zh_CN.po
=> Add translation support for ClockTow desklet

binaryclockdesklet@entelechy/files/binaryclockdesklet@entelechy/desklet.js, binaryclockdesklet@entelechy/files/binaryclockdesklet@entelechy/po/binaryclockdesklet@entelechy.pot, binaryclockdesklet@entelechy/files/binaryclockdesklet@entelechy/po/zh_CN.po
=> Add translation support for Binary clock desklet

shutdown@phpdreamer/files/shutdown@phpdreamer/desklet.js, shutdown@phpdreamer/files/shutdown@phpdreamer/po/shutdown@phpdreamer.pot, shutdown@phpdreamer/files/shutdown@phpdreamer/po/zh_CN.po
=> Add translation support for shutdown linux

commandOfTheDay@logg/files/desklet.js, commandOfTheDay@logg/files/po/commandOfTheDay@logg.pot, commandOfTheDay@logg/files/po/zh_CN.po
=> Add translation support for Command of the day desklet

battery@schorschii/files/battery@schorschii/po/de.po, battery@schorschii/files/battery@schorschii/po/zh_CN.po
=> battery@schorschii: add German translation & update template

stocks@fthuin/files/stocks@fthuin/desklet.js, stocks@fthuin/files/stocks@fthuin/po/stocks@fthuin.pot, stocks@fthuin/files/stocks@fthuin/po/zh_CN.po
=> Add translation support for Stocks Desklet

xkcd@rjanja/README.md, xkcd@rjanja/files/xkcd@rjanja/po/de.po
=> xkcd@rjanja: add German translation & copy README to parent directory

clockTow@armandobs14/files/clockTow@armandobs14/po/de.po
=> clockTow@armandobs14: add German translation

binaryclockdesklet@entelechy/files/binaryclockdesklet@entelechy/po/de.po
=> binaryclockdesklet@entelechy: add German translation

bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/po/de.po
=> bbcwx@oak-wood.co.uk: update German translation

quoteOfTheDay@tinnu/files/quoteOfTheDay@tinnu/po/de.po
=> quoteOfTheDay@tinnu: add German translation

shutdown@phpdreamer/files/shutdown@phpdreamer/po/de.po
=> shutdown@phpdreamer: add German translation

temperature@swalladge/files/temperature@swalladge/po/de.po, temperature@swalladge/files/temperature@swalladge/po/zh_CN.po, temperature@swalladge/files/temperature@swalladge/settings-schema.json
=> temperature@swalladge: add German translation & update l10n files

soundBox@scollins/files/soundBox@scollins/po/zh_CN.po
=> Update Chinese translation for Soundbox

reddit-reader@orangeshark/files/reddit-reader@orangeshark/po/zh_CN.po
=> Update Chinese translation for reddit reader desklet

battery@schorschii/files/battery@schorschii/po/zh_CN.po
=> Update Chinese translation for Battery Level Indicator

binaryclock2@euxneks/files/binaryclock2@euxneks/po/zh_CN.po
=> Update Chinese translation for Binary Clock²

calendar@schorschii/files/calendar@schorschii/desklet.js, calendar@schorschii/files/calendar@schorschii/po/calendar@schorschii.pot, calendar@schorschii/files/calendar@schorschii/po/zh_CN.po
=> Add translation support for Calendar

calendar@schorschii/files/calendar@schorschii/desklet.js, calendar@schorschii/files/calendar@schorschii/metadata.json, calendar@schorschii/files/calendar@schorschii/po/de.po, calendar@schorschii/files/calendar@schorschii/settings-schema.json
- added german translation
- background and text color of appointent number can now be changed separately
=> calendar@schorschii: Version 1.1

jalalidesklet@30yavash.com/files/jalalidesklet@30yavash.com/po/de.po, jalalidesklet@30yavash.com/files/jalalidesklet@30yavash.com/po/jalalidesklet@30yavash.com.pot
=> jalalidesklet@30yavash.com: add l10n support & German translation

devTools@scollins/files/devTools@scollins/po/zh_CN.po
=> Update Chinese translation for Developer Tools

bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/po/en.po
Reverts linuxmint/cinnamon-spices-desklets#89
@tipichris
=> Revert "bbcwx@oak-wood.co.uk: remove redundant en.po file"

netusage@30yavash.com/README.md, netusage@30yavash.com/files/netusage@30yavash.com/desklet.js, netusage@30yavash.com/files/netusage@30yavash.com/metadata.json, netusage@30yavash.com/files/netusage@30yavash.com/po/de.po, netusage@30yavash.com/files/netusage@30yavash.com/po/netusage@30yavash.com.pot, netusage@30yavash.com/info.json
=> netusage@30yavash.com: fix desklet and add l10n

clock@schorschii/files/clock@schorschii/po/zh_CN.po
=> Update Chinese translation for Analog Chronometer

netusage@30yavash.com/files/netusage@30yavash.com/po/zh_CN.po
=> Add Chinese translation for Network usage monitor

jalalidesklet@30yavash.com/files/jalalidesklet@30yavash.com/po/zh_CN.po
=> Add Chinese translation for Jalali Time and Date Desklet

WeatherUnderground@nightflame/files/WeatherUnderground@nightflame/desklet.js, WeatherUnderground@nightflame/files/WeatherUnderground@nightflame/po/WeatherUnderground@nightflame.pot, WeatherUnderground@nightflame/files/WeatherUnderground@nightflame/po/zh_CN.po
=> Add translation support for Weather Underground Desklet

lemondenewspaper@fthuin/files/po/zh_CN.po
=> Add Chinese translation support for LeMonde.fr Newspaper Unofficial

clock@schorschii/files/clock@schorschii/po/zh_CN.po
=> Update Chinese translation for Analog Chronometer 

bbcwx@oak-wood.co.uk/README.md, bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/po/es.po, bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/po/hu.po, bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/po/ja.po
Includes a couple of translation updates from https://translations.launchpad.net/bbcwx/
=> bbcwx@oak-wood.co.uk: updates to translations and README

bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/desklet.js, bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/marknote.js, bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/metadata.json
Code clean up to address warnings reported in issue #27. Remove some unused code.
=> bbcwx@oak-wood.co.uk: address issue #27 and clean up

quoteOfTheDay@tinnu/files/quoteOfTheDay@tinnu/po/ru.po
=> quoteOfTheDay@tinnu: add ru po

quoteOfTheDay@tinnu/CHANGELOG.md, quoteOfTheDay@tinnu/README.md, quoteOfTheDay@tinnu/files/quoteOfTheDay@tinnu/3.2/desklet.js, quoteOfTheDay@tinnu/files/quoteOfTheDay@tinnu/3.2/settings-schema.json, quoteOfTheDay@tinnu/files/quoteOfTheDay@tinnu/desklet.js
Use fortune to get a quote rather than parse the input file directly.  Updated README.md accordingly.  Added markdown formatting to CHANGELOG.md.
=> Update quoteOfTheDay to use fortune

quoteOfTheDay@tinnu/README.md
Provide instructions on how to install fortunes in languages other than English.
=> QuoteOfTheDay@tinnu: Add localization information to README

analog-clock@cobinja.de/files/analog-clock@cobinja.de/3.0/desklet.js
Fixes #172
also fixes timezone setting comparison
=> [analog-clock@cobinja.de] Fix disabled seconds hand reappearing after a Cinnamon restart

quoteOfTheDay@tinnu/CHANGELOG.md, quoteOfTheDay@tinnu/README.md, quoteOfTheDay@tinnu/files/quoteOfTheDay@tinnu/3.2/desklet.js, quoteOfTheDay@tinnu/files/quoteOfTheDay@tinnu/3.2/settings-schema.json, quoteOfTheDay@tinnu/files/quoteOfTheDay@tinnu/desklet.js, quoteOfTheDay@tinnu/files/quoteOfTheDay@tinnu/settings-schema.json
Added a couple of configuration options to allow the user more control over how `fortune` is called behind the scenes, and changed the way the timeout is handled, it seemed especially buggy in Cinnamon 3.2+
I started work on this quite awhile ago and just got around to finishing it up, so my branch is many commits behind master.  Please let me know if I should have done something about that (maybe git pull upstream master?) before creating this pull request!
=> quoteOfTheDay@tinnu: Added Advanced Configuration Options

quoteOfTheDay@tinnu/files/quoteOfTheDay@tinnu/po/quoteOfTheDay@tinnu.pot
Updated .pot file for new items to localize from the last update to this update.  Thanks for pointing this out, @Ilis , I know it's been awhile, please let me know if I've done anything incorrect here, I'm not familiar with this kind of file.
=> quoteOfTheDay@tinnu: Update .pot file

quoteOfTheDay@tinnu/files/quoteOfTheDay@tinnu/po/ru.po
=> quoteOfTheDay@tinnu: upd ru_po

.github/CODEOWNERS, commandOfTheDay@logg/info.json, jalalidesklet@30yavash.com/info.json, netusage@30yavash.com/info.json, powerUsage@hosvir.com/info.json, shutdown@phpdreamer/info.json
@logg @30yavash @hosvir @phpdreamer
Set authors of abandoned desklets to `none`
update CODEOWNERS
[commandOfTheDay@logg](https://cinnamon-spices.linuxmint.com/desklets/view/28)
[jalalidesklet@30yavash.com](https://cinnamon-spices.linuxmint.com/desklets/view/14)
[netusage@30yavash.com](https://cinnamon-spices.linuxmint.com/desklets/view/15)
[powerUsage@hosvir.com](https://cinnamon-spices.linuxmint.com/desklets/view/27)
[shutdown@phpdreamer](https://cinnamon-spices.linuxmint.com/desklets/view/22)
=> 5 desklets: set author to none

ganjine@mohammad-sn/files/ganjine@mohammad-sn/metadata.json, simple-system-monitor@ariel/files/simple-system-monitor@ariel/metadata.json, temperature@swalladge/files/temperature@swalladge/metadata.json
@mohammad-sn @arielandrade @swalladge fyi
=> 3 desklets: remove dangerous flags in metadata

.github/validate-spices-repo, README.md, cinnamon-spices-makepot, validate-spice
See README.md for usage of this scripts
=> Add `validate-spice` and `cinnamon-spices-makepot` scripts

soundBox@scollins/files/soundBox@scollins/po/tr.po
=> soundBox@scollins: add tr.po

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/po/ru.po
=> googleCalendar@javahelps.com add ru_po

deskNote@BrainAxe/files/deskNote@BrainAxe/desklet.js
=> Update desklet.js on deskNote@BrainAxe

deskNote@BrainAxe/files/deskNote@BrainAxe/po/deskNote@BrainAxe.pot
=> Create a deskNote@BrainAxe.pot

deskNote@BrainAxe/files/deskNote@BrainAxe/po/bg.po
Bulgarian localization for deskNote@BrainAxe.
=> bg.po for deskNote@BrainAxe

analog-clock@cobinja.de/files/analog-clock@cobinja.de/3.0/desklet.js
Apply this (no pun intended):
https://github.com/linuxmint/Cinnamon/commit/d4fc18e0d81051091324a4fe87c06e35f5865510
=> analog-clock@cobinja.de Performance improvement

battery@schorschii/files/battery@schorschii/desklet.js
@schorschii  Changed variable declarations from var to let. If the 'var' was intentional, then feel free to leave a comment and close this pull request.
=> Battery: Changed variable declarations from var to let.

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/po/bg.po
=> bg.po for googleCalendar@javahelps.com

simple-system-monitor@ariel/files/simple-system-monitor@ariel/po/bg.po
=> bgp.po for simple-system-monitor@ariel

analog-clock@cobinja.de/files/analog-clock@cobinja.de/3.0/desklet.js
=> analog-clock@cobinja.de Fix settings.py being non-executable

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/po/ru.po
=> googleCalendar@javahelps.com ru.po update

notes@schorschii/files/notes@schorschii/desklet.js, notes@schorschii/files/notes@schorschii/settings-schema.json
Hello @schorschii, thanks for the great desklet!
I made this modification because your desklet looks better with my desktop theme without a background. Feel free to suggest better ways to do this if it feels to hacky. 😉
=> notes@schorschii: Make it possible not to have a background

bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/po/ca.po
fix the abbreviations of days of the week for Catalan
http://www.unicode.org/cldr/charts/latest/summary/ca.html#1808
=> bbcwx@oak-wood.co.uk: Update Catalan translation

devTools@scollins/files/devTools@scollins/desklet.js, devTools@scollins/files/devTools@scollins/errorLog.js, devTools@scollins/files/devTools@scollins/extensions.js, devTools@scollins/files/devTools@scollins/inspect.js, devTools@scollins/files/devTools@scollins/sandbox.js, devTools@scollins/files/devTools@scollins/tabPanel.js, devTools@scollins/files/devTools@scollins/terminal.js, devTools@scollins/files/devTools@scollins/text.js, devTools@scollins/files/devTools@scollins/windows.js
- Updates imports to take advantage of new importer, and adds backwards compatibility
- Updates extension.js so extension inspection works on 3.8
Closes #244 
@collinss
=> devTools@scollins: Fix for Cinnamon 3.8

soundBox@scollins/files/soundBox@scollins/2.8/desklet.js
=> soundBox@scollins: Fix for Cinnamon 3.8

bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/desklet.js
The BBC have changed the address of their RSS feeds. This PR addresses these changes.
The solution is interim. Although the format of the RSS feeds has not changed, various fields are being returned empty. I'll give it a few weeks and if this looks permanent I'll remove the affected fields from the desklet.
=> bbcwx@oak-wood.co.uk: BBC endpoint changed

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/po/fr.po
The translation is the same for "fr" and "fr-CA" and should work on both locale. I'm not really sure how to specify this information in this file...
@slgobinath
=> spice name: googleCalendar@javahelps.com / Create fr.po

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/po/fr.po
Small mistake in "may" translation
=>  googleCalendar@javahelps.com: Update fr.po

googleCalendar@javahelps.com/README.md, googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/desklet.js, googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/lib/utility.js, googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/metadata.json
Fix https://github.com/linuxmint/cinnamon-spices-desklets/issues/296 and added support for Cinnamon 3.8
@NikoKrause  please check this PR.
Thanks
=> Fix #296 and support Cinnamon 3.8

netusage@30yavash.com/README.md, netusage@30yavash.com/files/netusage@30yavash.com/desklet.js
* Fix issue #279 using the  code developed by @jaszhix to select the Network manager
* Fix continuous output of test data to the error log
* Minor tidy up of code layout
* Provide additional information in README.md 
This  has been tested using a LiveUSB of the cinnamon spin of Fedora 27 as well as Mint 18.3
This should also fix the problem with Fedora 27 mentioned in a comment on the Cinnamon Desklets web site by @tikondrus - could he please check that his issue is fixed by this commit
=> netusage@30yavash.com fix issue 279

analog-clock@cobinja.de/files/analog-clock@cobinja.de/2.8/desklet.js, analog-clock@cobinja.de/files/analog-clock@cobinja.de/3.0/desklet.js
- Fix tz clock update after timezone change (Fixes https://github.com/linuxmint/cinnamon-spices-desklets/issues/268)
- Fix file handling for newer GLib/GdkPixbuf versions
=> analog-clock@cobinja.de 2 bugfixes

top@ryannerd/files/top@ryannerd/metadata.json
=> Top: Allowed Cinnamon version changed to also support Fedora

simple-system-monitor@ariel/files/simple-system-monitor@ariel/desklet.js
=> simple-system-monitor@ariel: Fix for Cinnamon 3.8

top@ryannerd/README.md, top@ryannerd/files/top@ryannerd/desklet.js, top@ryannerd/files/top@ryannerd/metadata.json
=> top@ryannerd: Fix for PID display where first digit is missing

README.md
Here are a few typo fixes for the readme. This is my first PR ever, so apologies if I did something wrong along the way.
=> cinnamon-spices-desklets: A few typo corrections for the readme

.gitignore, README.md, gulpfile.js, package-lock.json, package.json
See https://github.com/linuxmint/cinnamon-spices-applets/pull/2075
=> repo: Add a utility for reloading desklets on code change

calendar@schorschii/files/calendar@schorschii/po/tr.po
calendar@schorschii: add tr.po
=> calendar@schorschii: add tr.po

battery@schorschii/files/battery@schorschii/po/tr.po
=> battery@schorschii: add tr.po

simple-system-monitor@ariel/files/simple-system-monitor@ariel/po/tr.po
simple-system-monitor@ariel: add tr.po
=> simple-system-monitor@ariel: add tr.po

notes@schorschii/files/notes@schorschii/po/tr.po
=> notes@schorschii: add tr.po

diskspace@schorschii/files/diskspace@schorschii/po/tr.po
calendar@schorschii: add tr.po
=> diskspace@schorschii: add tr.po

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/lib/xdate.js
Hi @slgobinath, hi @jaszhix,
This version of xdate.js fixes a time zone bug.
Best regards.
=> [googleCalendar@javahelps.com] xdate.js - Time zone fixes

diskspace@schorschii/files/diskspace@schorschii/desklet.js, diskspace@schorschii/files/diskspace@schorschii/metadata.json
Missing "let" for variable "pathparts" causes a crash on latest cinnamon version
=> diskspace@schorschii: fixed missing variable declaration

googleCalendar@javahelps.com/README.md
=> Add missing dependencies

googleCalendar@javahelps.com/README.md, googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/desklet.js, googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/py/google_calendar.py
Fix #389
@jaszhix please check this PR.
=> Move calendar.dat to config folder

InternetTimeDesklet@stefan/README.md
Just did some formatting of the text. (Headline & Links)
=> InternetTimeDesklet@stefan :  updated README.md

soundBox@scollins/files/soundBox@scollins/po/sv.po
Add Swedish translation
Btw, Start player button don't work.
=> soundBox@scollins: add sv.po

diskspace@schorschii/files/diskspace@schorschii/po/sv.po
=> diskspace@schorschii: add sv.po

calendar@schorschii/files/calendar@schorschii/po/calendar@schorschii.pot, calendar@schorschii/files/calendar@schorschii/po/sv.po
=> calendar@schorschii: add sv.po

devTools@scollins/files/devTools@scollins/po/sv.po
=> devTools@scollins: add sv.po

simple-system-monitor@ariel/files/simple-system-monitor@ariel/4.0/stylesheet.css, simple-system-monitor@ariel/files/simple-system-monitor@ariel/stylesheet.css
A bit wider mainContainer to make room for Swedish (and others) translation on heavy load.
=> simple-system-monitor@ariel: Update 4.0/stylesheet.css

notes@schorschii/files/notes@schorschii/img/index.csv
The current None theme is not listed in index.csv therefore settings are not properly applied if it is selected, this commit fixes that bug.
=> notes@schorschii: Fix None theme

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/desklet.js
=> Fix showing only the first day of multiday events

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/metadata.json
@slgobinath 
This is a simple modification of `metadata.json` to make this fabulous desklet usable with Cinnamon 4.2.
=> Making usable with Cinnamon 4.2

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/desklet.js, googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/settings-schema.json
Hi @slgobinath,
I propose some improvements to calendar management in Settings.
Cinnamon 4.0:
Cinnamon 4.2:
This list is populated by your `google_calendar.py --list-calendars`. It replaces the calendarName field; but in desklet.js the this.calendarName variable is set from the data of this list.
This also avoids typing errors or comma omissions.
I hope this will suit you.
Best regards.
Claudiux
=> [googleCalendar@javahelps.com] - Improvements to calendar management in Settings

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/po/googleCalendar.pot, googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/settings-schema.json
Hi @brownsr, hi @slgobinath,
I have updated some strings in `settings-schema.json` (new strings in #439) and I propose a new pot file containing them.
@brownsr Can you merge this branch with your master one, please?
Best regards.
Claudiux
=> [googleCalendar@javahelps.com] New strings in settings-schema.json and new pot file

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/po/fr.po
Made with the new pot file (#440).
=> [googleCalendar@javahelps.com] - New fr.po file

netusage@30yavash.com/files/netusage@30yavash.com/metadata.json
Added "4.2" to cinnamon-version in metadata.json to allow use with Cinnamon 4.2
=> netusage@yavash.com - Update for Cinnamon 4.2

simple-system-monitor@ariel/files/simple-system-monitor@ariel/metadata.json
Added "4.2" to cinnamon-version in metadata.json to allow use with Cinnamon 4.2
=> simple-system-monitor@ariel - Update for Cinnamon 4.2

ViennaTextBasedWeather@f-istvan/README.md, ViennaTextBasedWeather@f-istvan/files/ViennaTextBasedWeather@f-istvan/desklet.js, ViennaTextBasedWeather@f-istvan/files/ViennaTextBasedWeather@f-istvan/settings-schema.json
ViennaTextBasedWeather@f-istvan, fix #444
=> ViennaTextBasedWeather@f-istvan, fix #444

TimeAndDate@nightflame/files/TimeAndDate@nightflame/po/it.po, analog-clock@cobinja.de/files/analog-clock@cobinja.de/po/it.po, battery@schorschii/files/battery@schorschii/po/it.po, bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/po/it.po, binaryclock2@euxneks/files/binaryclock2@euxneks/po/it.po, calendar@deeppradhan/files/calendar@deeppradhan/po/it.po, calendar@schorschii/files/calendar@schorschii/po/it.po, clock@schorschii/files/clock@schorschii/po/it.po, clockTow@armandobs14/files/clockTow@armandobs14/po/it.po, commandOfTheDay@logg/files/commandOfTheDay@logg/po/it.po, deskNote@BrainAxe/files/deskNote@BrainAxe/po/it.po, simple-system-monitor@ariel/files/simple-system-monitor@ariel/po/it.po, soundBox@scollins/files/soundBox@scollins/po/it.po, temperature@swalladge/files/temperature@swalladge/po/it.po, xkcd@rjanja/files/xkcd@rjanja/po/it.po
Hi, I've added Italian translations to some desklets.
=> New Italian translations

clock@schorschii/files/clock@schorschii/po/sv.po
=> clock@schorschii: add sv.po

calculator@scollins/files/calculator@scollins/po/sv.po
=> calculator@scollins: add sv.po

deskNote@BrainAxe/files/deskNote@BrainAxe/po/sv.po
=> deskNote@BrainAxe: add sv.po

diskspace@schorschii/files/diskspace@schorschii/desklet.js
Bugfix: replace INOUT by BIDIRECTIONAL.
=> [diskspace@schorschii] desklet.js: replace INOUT by BIDIRECTIONAL

cpuload@kimse/files/cpuload@kimse/desklet.js, cpuload@kimse/files/cpuload@kimse/settings-schema.json
@ipimpat 
I've added switch for presenting total CPU usage (not separated by core). Refresh interval option has been also introduced.
=> cpuload@kimse: Add total CPU usage switch and refresh interval

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/lib/xdate.js
Fix #459 
@brownsr could you please check this PR?
Thanks
=> googleCalendar@javahelps.com: Fix Google Calendard showing events one day late

battery@schorschii/files/battery@schorschii/desklet.js, clock@schorschii/README.md, clock@schorschii/files/clock@schorschii/desklet.js
clock@schorschii
- use decodeURIComponent() to support paths (custom images) with spaces
battery@schorschii
- fix plug/flash icon flickering
=> Schorschii desklet fixes

netusage@30yavash.com/files/netusage@30yavash.com/metadata.json
=> netusage@30yavash.comv 1.0.4.2 Update for 4.4 only

simple-system-monitor@ariel/files/simple-system-monitor@ariel/metadata.json
=> simple-system-monitor@ariel v 1.0.0.2  Update for 4.4 only

cpuload@kimse/files/cpuload@kimse/desklet.js, cpuload@kimse/files/cpuload@kimse/po/cpuload@kimse.pot, cpuload@kimse/files/cpuload@kimse/po/de.po
Hi @ipimpat , I created a translation template file and the German translation. Furthermore, I propose the following new features:
- optional thin design
- static or dynamic circle color
- adjustments for HiDPI screens
- text horizontally centered by style attribute (text-align:center)
=> cpuload@kimse: translation, improvements, fixes

cpuload@kimse/files/cpuload@kimse/desklet.js, cpuload@kimse/files/cpuload@kimse/metadata.json, cpuload@kimse/files/cpuload@kimse/po/cpuload@kimse.pot, cpuload@kimse/files/cpuload@kimse/po/de.po, cpuload@kimse/files/cpuload@kimse/settings-schema.json
Hi @ipimpat , here is my second pull request for the new features:
- optional thin design
- static or dynamic circle color
=> cpuload@kimse proposals: thin design and color options

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/metadata.json
=> [googleCalendar@javahelps.com] Now compatible with Cinnamon 4.4

diskspace@schorschii/files/diskspace@schorschii/desklet.js, diskspace@schorschii/files/diskspace@schorschii/metadata.json
=> diskspace@schorschii: fix RAM calculation

analog-clock@cobinja.de/files/analog-clock@cobinja.de/po/sv.po
=> analog-clock@cobinja.de: add sv.po

hostcheck@schorschii/files/hostcheck@schorschii/desklet.js, hostcheck@schorschii/files/hostcheck@schorschii/po/diskspace@schorschii.pot, hostcheck@schorschii/files/hostcheck@schorschii/po/sv.po
Add Swedish translation and some fix for missing translation strings
=> hostcheck@schorschii: add sv.po

calendar@deeppradhan/files/calendar@deeppradhan/po/sv.po
Add Swedish translation
About translation don't work.
Translatable months/days should also be appreciated.
=> calendar@deeppradhan: add sv.po

battery@schorschii/files/battery@schorschii/po/sv.po
=> battery@schorschii: add sv.po

reddit-reader@orangeshark/files/reddit-reader@orangeshark/po/sv.po
=> reddit-reader@orangeshark: add sv.po

diskspace@schorschii/files/diskspace@schorschii/po/sv.po
Update Swedish translation from POT
=> diskspace@schorschii: Update sv.po

calculator@scollins/files/calculator@scollins/po/sv.po
Update Swedish translation from POT
=> calculator@scollins: Update sv.po

netusage@30yavash.com/files/netusage@30yavash.com/po/netusage@30yavash.com.pot, netusage@30yavash.com/files/netusage@30yavash.com/po/sv.po
Add Swedish translation and make applet settings translatable
=> netusage@30yavash.com: add sv.po

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/po/sv.po
=> googleCalendar@javahelps.com: add sv.po

diskspace@schorschii/files/diskspace@schorschii/desklet.js, diskspace@schorschii/files/diskspace@schorschii/metadata.json
use decodeURIComponent() to support paths with spaces
=> diskspace@schorschii: v1.6 bugfix

diskspace@schorschii/files/diskspace@schorschii/desklet.js, diskspace@schorschii/files/diskspace@schorschii/metadata.json, diskspace@schorschii/files/diskspace@schorschii/po/de.po, diskspace@schorschii/files/diskspace@schorschii/po/diskspace@schorschii.pot, diskspace@schorschii/files/diskspace@schorschii/settings-schema.json
- add setting for on click action: open file manager, partition editor or nothing
=> diskspace@schorschii: new on click options

commandResult@ZimiZones/files/commandResult@ZimiZones/4.0/desklet.js, commandResult@ZimiZones/files/commandResult@ZimiZones/4.0/settings-schema.json, commandResult@ZimiZones/files/commandResult@ZimiZones/4.0/stylesheet.css, commandResult@ZimiZones/files/commandResult@ZimiZones/desklet.js, commandResult@ZimiZones/files/commandResult@ZimiZones/settings-schema.json, commandResult@ZimiZones/files/commandResult@ZimiZones/stylesheet.css
Now you can change text alignment in settings
=> commandResult@ZimiZones: Now you can change text alignment in settings

mintoo@sujitagarwal/README.md, mintoo@sujitagarwal/files/mintoo@sujitagarwal/desklet.js, mintoo@sujitagarwal/files/mintoo@sujitagarwal/stylesheet.css
1. Removed double click functionality for buttons.
2. Added Single click functionality for buttons.
3. Removed unsupported CSS properties and added absolute values for sizes.
@brownsr FYI
=> Minor bug fixes and functionality enhancements for Mintoo

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/po/eu.po
=> googleCalendar@javahelps.com add eu.po

commandResult@ZimiZones/files/commandResult@ZimiZones/4.0/desklet.js, commandResult@ZimiZones/files/commandResult@ZimiZones/4.0/settings-schema.json, commandResult@ZimiZones/files/commandResult@ZimiZones/desklet.js, commandResult@ZimiZones/files/commandResult@ZimiZones/settings-schema.json
=> commandResult@ZimiZones: Fix font selection

googleCalendar@javahelps.com/README.md, googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/metadata.json
=> googleCalendar@javahelps.com support Cinnamon 4.6 fix #530

simple-system-monitor@ariel/files/simple-system-monitor@ariel/metadata.json
* Fix for Cinnamon 4.6 to 5.2 (Mint 20) by additions to cinnamon-version in metadata.json
=> simple-system-monitor@ariel Version 1.0.1 Fix for Cinnamon 4.6 to 5.2

netusage@30yavash.com/files/netusage@30yavash.com/metadata.json
* Fix for Cinnamon 4.6 to 5.2 (Mint 20) by additions to cinnamon-version in metadata.json
=> netusage@30yavash.com Version 1.0.5 Fix for Cinnamon 4.6 to 5.2 (Mint 20)

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/desklet.js
@slgobinath 
Hi,
This PR solves that:
```
Cjs-Message: 13:13:48.834: JS WARNING: [/usr/share/cinnamon/js/misc/fileUtils.js line 210 > Function 88]: reference to undefined property "onDeskletFormatChanged"
Cjs-Message: 13:13:48.848: JS LOG: [LookingGlass/info] Loaded desklet googleCalendar@javahelps.com in 20 ms
```
=> [googleCalendar@javahelps.com] Update desklet.js - Typo fixed

cpuload@kimse/README.md, cpuload@kimse/files/cpuload@kimse/desklet.js, cpuload@kimse/files/cpuload@kimse/metadata.json, cpuload@kimse/files/cpuload@kimse/po/cpuload@kimse.pot, cpuload@kimse/files/cpuload@kimse/po/de.po, cpuload@kimse/files/cpuload@kimse/settings-schema.json
This pull request is mainly a refactoring of the code.
Main improvement is that the file system reading operation has been changed from blocking to non-blocking (getCpuActivitySample and readProcStatFileAsync), which hopefully will improve overall stability, but comments regarding that is most welcome, because this is mainly a learning experience for me.
I have been using the desklet with the modifications, for a couple of weeks now with LM20 and had no issues.
=> Cpuload@kimse refactor

diskspace@schorschii/files/diskspace@schorschii/desklet.js, diskspace@schorschii/files/diskspace@schorschii/metadata.json, diskspace@schorschii/files/diskspace@schorschii/po/de.po, diskspace@schorschii/files/diskspace@schorschii/po/diskspace@schorschii.pot, diskspace@schorschii/files/diskspace@schorschii/settings-schema.json, diskspace@schorschii/files/diskspace@schorschii/stylesheet.css
- new "compact" design
- option to hide the text
=> diskspace@schorschii: new design

yfquotes@thegli/README.md, yfquotes@thegli/files/yfquotes@thegli/desklet.js, yfquotes@thegli/files/yfquotes@thegli/metadata.json, yfquotes@thegli/files/yfquotes@thegli/settings-schema.json
-  add setting to disable quote name hyperlink.
-  remove invalid quote symbol from default list.
=> yfquotes@thegli: add option to disable hyperlink in quote name, remove invalid quote symbol

diskspace@schorschii/README.md, diskspace@schorschii/files/diskspace@schorschii/desklet.js, diskspace@schorschii/files/diskspace@schorschii/metadata.json, diskspace@schorschii/files/diskspace@schorschii/po/de.po, diskspace@schorschii/files/diskspace@schorschii/po/diskspace@schorschii.pot, diskspace@schorschii/files/diskspace@schorschii/settings-schema.json
Adds the ability to display the swap usage
=> diskspace@schorschii: add swap functionality

TimeAndDate@nightflame/files/TimeAndDate@nightflame/po/ko.po
Added Korean language file for timedate desklet.
=> Added Korean language file

TimeAndDate@nightflame/files/TimeAndDate@nightflame/po/hu.po, calculator@scollins/files/calculator@scollins/po/hu.po
I added the Hungarian translation to some desklets.
=> New Hungarian translations

system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/settings-schema.json
=> system-monitor-graph: fix typo

yfquotes@thegli/files/yfquotes@thegli/po/ko.po
- Korean translation for Yahoo Finance Quotes
=> Added Korean translation for Yahoo Finance Quotes

notes@schorschii/files/notes@schorschii/po/ru.po
Upload `ru.po` file by @xbow007
Closes https://github.com/linuxmint/cinnamon-spices-desklets/issues/583
=> notes@schorschii: Add Russian l10n, update l10n template

notes@schorschii/files/notes@schorschii/po/de.po, notes@schorschii/files/notes@schorschii/po/notes@schorschii.pot, notes@schorschii/files/notes@schorschii/settings-schema.json
=> [notes@schorschii] fix tooltip

diskspace@schorschii/files/diskspace@schorschii/desklet.js, diskspace@schorschii/files/diskspace@schorschii/metadata.json, diskspace@schorschii/files/diskspace@schorschii/po/de.po, diskspace@schorschii/files/diskspace@schorschii/po/diskspace@schorschii.pot, diskspace@schorschii/files/diskspace@schorschii/settings-schema.json
=> diskspace@schorschii: add more text options

bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/desklet.js
Original issue https://github.com/tipichris/bbcwx/issues/42 and original PR https://github.com/tipichris/bbcwx/pull/43
=> bbcwx: Check for 'Not available' for bbc observations

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/lib/utility.js
=> [ googleCalendar@javahelps.com] Clear the resources after reading from spawned process

clocket@tirtha/README.md, clocket@tirtha/files/clocket@tirtha/desklet.js, clocket@tirtha/files/clocket@tirtha/index.html, clocket@tirtha/files/clocket@tirtha/settings-schema.json, clocket@tirtha/info.json
added some new features to clocket@tirtha auto update feature, feedback display and more customization .
And as per your request I have removed all unnecessary embedded codes I found .
=> added some new feature to clocket@tirtha  and removed embedded codes as much as possible.

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/po/es.po
A Linux Mint user sent me the translation and I'm creating the PR for him.
=> googleCalendar@javahelps.com: Add Spanish translation

diskspace@schorschii/files/diskspace@schorschii/po/es.po
Added Spanish translation, thanks to Venom!
=> diskspace@schorschii: Spanish translation

calendar@schorschii/files/calendar@schorschii/po/es.po, clock@schorschii/files/clock@schorschii/po/es.po, notes@schorschii/files/notes@schorschii/po/es.po
More Spanish translations, thanks to Venom!
- calendar@schorschii
- notes@schorschii
- clock@schorschii
=> More Spanish translations

diskspace@schorschii/files/diskspace@schorschii/po/de.po, diskspace@schorschii/files/diskspace@schorschii/po/es.po
Added new German & Spanish translations for text introduced with #706
=> diskspace@schorschii: add new translations

cpuload@kimse/files/cpuload@kimse/po/cpuload@kimse.pot, cpuload@kimse/files/cpuload@kimse/po/de.po
- added new text introduced with #699 to template file
- added German translation for new text
=> New cpuload@kimse translations

cpuload@kimse/files/cpuload@kimse/po/de.po, cpuload@kimse/files/cpuload@kimse/po/es.po
- added Spanish translation - closes #715 
- improved German translation
=> cpuload@kimse Spanish/German translation

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/desklet.js, googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/lib/utility.js, googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/po/googleCalendar.pot, googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/settings-schema.json, googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/writeEvents.sh
Fix https://github.com/linuxmint/cinnamon-spices-desklets/issues/664
Fix https://github.com/linuxmint/cinnamon-spices-desklets/issues/709
=> googleCalendar@javahelps.com: Fix fill calendar names command

analog-clock@cobinja.de/files/analog-clock@cobinja.de/po/ru.po, analog-clock@cobinja.de/files/analog-clock@cobinja.de/po/uk.po, battery@schorschii/files/battery@schorschii/po/ru.po, battery@schorschii/files/battery@schorschii/po/uk.po
Added two localizations to two desklets, **Russian** and **Ukrainian** to
- `analog-clock@cobinja.de`
- `battery@schorschii`
=> Added two localizations to two desklets

calc@ptandler/README.md, calc@ptandler/files/calc@ptandler/desklet.js, calc@ptandler/files/calc@ptandler/metadata.json, calc@ptandler/files/calc@ptandler/stylesheet.css
=> Calc@ptandler v.02 added expression & result history

yfquotes@thegli/README.md, yfquotes@thegli/files/yfquotes@thegli/desklet.js, yfquotes@thegli/files/yfquotes@thegli/metadata.json, yfquotes@thegli/files/yfquotes@thegli/po/da.po, yfquotes@thegli/files/yfquotes@thegli/po/de.po, yfquotes@thegli/files/yfquotes@thegli/po/hu.po, yfquotes@thegli/files/yfquotes@thegli/po/it.po, yfquotes@thegli/files/yfquotes@thegli/po/ko.po, yfquotes@thegli/files/yfquotes@thegli/po/pt_BR.po, yfquotes@thegli/files/yfquotes@thegli/po/ru.po, yfquotes@thegli/files/yfquotes@thegli/po/yfquotes@thegli.pot, yfquotes@thegli/files/yfquotes@thegli/settings-schema.json
This PR updates language files of the yfquotes@thegli desklet: 
- add/remove fields to the existed languages according to the last version of the desklet
- add ru.po translation
=> yfquotes: add ru.po

system-monitor-graph@rcassani/README.md, system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/desklet.js, system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/metadata.json, system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/po/de.po, system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/po/system-monitor-graph@rcassani.pot, system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/settings-schema.json
This adds the option to display the swap usage and a German translation.
@rcassani , what do you think?
=> system-monitor-graph@rcassani: add option to display swap usage

bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/po/ru.po, binaryclock2@euxneks/files/binaryclock2@euxneks/po/ru.po
Updated/Added Russian localization for bbcwx and binaryclock2
=> Updated/Added Russian localization

system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/desklet.js, system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/settings-schema.json
=> Bugfix: Solve #782

InternetTimeDesklet@stefan/files/InternetTimeDesklet@stefan/desklet.js
The calculation for netBeats was off so I tried to fix it - this is what I came up with.
Some lines were tidied by my vim plugins. Lines 75-91 are really relevant.
original author was @stefan12O
=> InternetTimeDesklet@stefan: Fixed netBeat (Swatch Internet Time) Calculation

bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/desklet.js
Add support for libsoup3. For more info see https://github.com/linuxmint/cinnamon/commit/76224fe409d074f8a44c70e4fd5e1289f92800b9
@tipichris
=> [bbcwx@oak-wood.co.uk] Add support for libsoup3

cryptocoins@pbojan/files/cryptocoins@pbojan/desklet.js
Add support for libsoup3. For more info see https://github.com/linuxmint/cinnamon/commit/76224fe409d074f8a44c70e4fd5e1289f92800b9
@pbojan
=> [cryptocoins@pbojan] Add support for libsoup3

clocket@tirtha/files/clocket@tirtha/desklet.js
Add support for libsoup3. For more info see https://github.com/linuxmint/cinnamon/commit/76224fe409d074f8a44c70e4fd5e1289f92800b9
@tirtharajsinha
=> [clocket@tirtha] Add support for libsoup3

yfquotes@thegli/files/yfquotes@thegli/desklet.js
Add support for libsoup3. For more info see https://github.com/linuxmint/cinnamon/commit/76224fe409d074f8a44c70e4fd5e1289f92800b9
@thegli
=> [yfquotes@thegli] Add support for libsoup3

bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/po/it.po, simple-system-monitor@ariel/files/simple-system-monitor@ariel/po/it.po, timelet@linuxedo.com/files/timelet@linuxedo.com/po/it.po, yfquotes@thegli/files/yfquotes@thegli/po/it.po
Hi,
I've reviewed and added some new Italian translations to various desklets.
Have a nice day :D
=> Adds new Italian translations to various desklets

calculator@scollins/files/calculator@scollins/desklet.js, calculator@scollins/files/calculator@scollins/metadata.json
This fixes the broken layout and keyboard input in Mint 21.
=> calculator@scollins: fixes for Mint 21

yfquotes@thegli/README.md, yfquotes@thegli/files/yfquotes@thegli/desklet.js, yfquotes@thegli/files/yfquotes@thegli/metadata.json, yfquotes@thegli/files/yfquotes@thegli/po/yfquotes@thegli.pot, yfquotes@thegli/files/yfquotes@thegli/settings-schema.json
- perform required authentication steps in order to get API version 7 working again
- set default API version to 7, as version 6 stopped working
- fix libsoup3-specific code
=> yfquotes@thegli: adapt to recent changes in Yahoo Finance Quotes API, fix libsoup3

diskspace@schorschii/files/diskspace@schorschii/desklet.js
In some cases the desklet diskspace@schorschii has problems parsing the output of `free`. This leads to wrong values in the desklet. This is because in my case there is no whitespace between `Speicher:` and `33372061696` anymore.
I have fixed the problem and refactored the code a little.
- the paths for "ram" and "swap" have been merged
- introduction of a separate method for parsing the output of `free`
Hope that helps.
PS:
Some translations may help understand the picture:
- Speicher - memory
- frei - free
- Belegter Speicherplatz - used memory
=> diskspace@schorschii: fix mem parsing

show-remote-ip-desklet@nejdetckenobi/files/show-remote-ip-desklet@nejdetckenobi/desklet.js, show-remote-ip-desklet@nejdetckenobi/files/show-remote-ip-desklet@nejdetckenobi/metadata.json, show-remote-ip-desklet@nejdetckenobi/files/show-remote-ip-desklet@nejdetckenobi/settings-schema.json, show-remote-ip-desklet@nejdetckenobi/files/show-remote-ip-desklet@nejdetckenobi/stylesheet.css
- Added proper settings
- Allow showing ip4, ip6 or both
- Fix urls so correct ip address type is reliably returned.
@nejdetckenobi
=> show-remote-ip-desklet@nejdetckenobi: Add soup 3 compatibility, plus a few improvements.

commandResult@ZimiZones/files/commandResult@ZimiZones/4.0/desklet.js, commandResult@ZimiZones/files/commandResult@ZimiZones/4.0/settings-schema.json, commandResult@ZimiZones/files/commandResult@ZimiZones/desklet.js, commandResult@ZimiZones/files/commandResult@ZimiZones/settings-schema.json
Thanks to [Gustavo Santos](https://github.com/glgomes) for the changes. Which I made to my own copy of the desklet. Figured I could save others some time as well by just having these changes present from the download system. Also, the loading message is disabled as per Gustavo's suggestion.
=> updates frequency is now in seconds rather than miniutes

battery@schorschii/files/battery@schorschii/desklet.js, battery@schorschii/files/battery@schorschii/po/battery@schorschii.pot, battery@schorschii/files/battery@schorschii/po/ca.po, battery@schorschii/files/battery@schorschii/po/da.po, battery@schorschii/files/battery@schorschii/po/de.po, battery@schorschii/files/battery@schorschii/po/es.po, battery@schorschii/files/battery@schorschii/po/hu.po, battery@schorschii/files/battery@schorschii/po/it.po, battery@schorschii/files/battery@schorschii/po/pt_BR.po, battery@schorschii/files/battery@schorschii/po/ru.po, battery@schorschii/files/battery@schorschii/po/sk.po, battery@schorschii/files/battery@schorschii/po/sv.po, battery@schorschii/files/battery@schorschii/po/tr.po, battery@schorschii/files/battery@schorschii/po/uk.po, battery@schorschii/files/battery@schorschii/po/zh_CN.po
- Fixing Array.toString warnings similar to #856
- Updating translation files
cc: @schorschii
=> battery@schorschii: Fix Array warnings and update translations

reddit-reader@orangeshark/files/reddit-reader@orangeshark/desklet.js
Tests ok in 2 and 3.
To test with soup 3, edit /usr/share/cinnamon/js/ui/environment.js and change the soup version from 2.4 to 3.0. Save and restart cinnamon.
@NikoKrause
=> reddit-reader@orangeshark: Add soup 3 compatibility.

yfquotes@thegli/README.md, yfquotes@thegli/files/yfquotes@thegli/desklet.js, yfquotes@thegli/files/yfquotes@thegli/metadata.json, yfquotes@thegli/files/yfquotes@thegli/po/de.po, yfquotes@thegli/files/yfquotes@thegli/po/yfquotes@thegli.pot, yfquotes@thegli/files/yfquotes@thegli/settings-schema.json
This new, optional setting may help in high-load situations.
=> yfquotes@thegli: add setting to configure HTTP User-Agent request header

ViennaTextBasedWeather@f-istvan/files/ViennaTextBasedWeather@f-istvan/desklet.js
Tested, seems fine.
To test with soup 3, edit /usr/share/cinnamon/js/ui/environment.js and change the soup version from 2.4 to 3.0. Save and restart cinnamon.
@f-istvan
=> ViennaTextBasedWeather@f-istvan: Add Soup 3 compatibility.

simple-system-monitor@ariel/files/simple-system-monitor@ariel/metadata.json
=> simple-system-monitor@ariel: Fix metadata for Cinnamon <5.8

timelet@linuxedo.com/files/timelet@linuxedo.com/desklet.js, timelet@linuxedo.com/files/timelet@linuxedo.com/themes/digital.js, timelet@linuxedo.com/files/timelet@linuxedo.com/themes/flair.js, timelet@linuxedo.com/files/timelet@linuxedo.com/themes/gotham.js, timelet@linuxedo.com/files/timelet@linuxedo.com/themes/jelly.js, timelet@linuxedo.com/files/timelet@linuxedo.com/themes/metro.js, timelet@linuxedo.com/files/timelet@linuxedo.com/themes/theme.js, timelet@linuxedo.com/files/timelet@linuxedo.com/themes/themes.js
Make compatible with Mint 21.2
+Fix desklet not working in live image.
Fixes #865
@slgobinath
=> timelet@linuxedo.com Mint 21.2 update

diskspace@schorschii/files/diskspace@schorschii/po/ca.po
Update the Catalan translation of @schorschii 's desklet.
Sorry to bother you with this twice :(
=> diskspace@schorschii: update Catalan translation

cpuload@kimse/files/cpuload@kimse/po/ca.po
Made the Catalan translation for @ipimpat 's desklet.
=> cpuload@kimse: created Catalan translation

clock@schorschii/files/clock@schorschii/po/ca.po
Update the Catalan translation of @schorschii 's desklet.
=> clock@schorschii: updated Catalan translation

simple-system-monitor@ariel/files/simple-system-monitor@ariel/po/ca.po
Updated the Catalan translation of @arielandrade 's desklet.
=> simple-system-monitor@ariel: updated Catalan translation

system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/po/ca.po, system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/po/es.po
Two commits to update @rcassani 's desklet.
- Created the Catalan translation of the desklet.
- Updated this desklet's Spanish translation.
=> system-monitor-graph@rcassani: ca es translations

notes@schorschii/files/notes@schorschii/po/ca.po
Made @schorschii notes desklet's Catalan translation up-to-date.
=> notes@schorschii: updated Catalan translation

devTools@scollins/files/devTools@scollins/po/ca.po, devTools@scollins/files/devTools@scollins/po/es.po
- Created the Catalan and Spanish translations for this @collinss 's desklet.
- Still, there are a few strings left untranslated, as I am not sure my translation will be clearer than the originals.
- The first Catalan po file was another desklet's po file I uploaded by mistake.
=> devTools@scollins: new translations

timelet@linuxedo.com/files/timelet@linuxedo.com/po/ca.po, timelet@linuxedo.com/files/timelet@linuxedo.com/po/es.po
Changes to this @linuxedo.com 's desklet
- Minor corrections to Spanish translation
- Created the Catalan translation
=> timelet@linuxedo.com: translation updates

show-remote-ip-desklet@nejdetckenobi/files/show-remote-ip-desklet@nejdetckenobi/po/ca.po, show-remote-ip-desklet@nejdetckenobi/files/show-remote-ip-desklet@nejdetckenobi/po/es.po, show-remote-ip-desklet@nejdetckenobi/files/show-remote-ip-desklet@nejdetckenobi/po/show-remote-ip-desklet@nejdetckenobi.pot
Changes to this @nejdetckenobi 's desklet
- Created the po template file to make it possible to translate the desklet.
- Created the Spanish po file (translation).
- Created the Catalan po file (translation).
=> show-remote-ip-desklet@nejdetckenobi: first translations

binaryclock2@euxneks/files/binaryclock2@euxneks/po/ca.po, binaryclock2@euxneks/files/binaryclock2@euxneks/po/es.po
Updated the Catalan and Spanish translation of this @euxneks 's desklet.
=> binaryclock2@euxneks: updated translations

calendar@deeppradhan/files/calendar@deeppradhan/po/ca.po
Catalan translation for this @kanchudeep 's desklet.
=> calendar@deeppradhan: created Catalan translation

googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/po/ca.po, googleCalendar@javahelps.com/files/googleCalendar@javahelps.com/po/es.po
Changes in this PR to @javahelps.com 's desklet (renamed to @slgobinath ?)
- Created Catalan translation.
- Fixed a minor type error in the Spanish translation.
=> googleCalendar@javahelps.com: updated translations

bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/5.4/desklet.js
@tipichris A quick PR to remove an unused import.
=> bbcwx@oak-wood.co.uk: Remove unused import

simple-system-monitor@ariel/files/simple-system-monitor@ariel/5.8/desklet.js
=> simple-system-monitor@ariel: Fix toString() warning and remove unused import

simple-system-monitor@ariel/files/simple-system-monitor@ariel/po/bg.po, simple-system-monitor@ariel/files/simple-system-monitor@ariel/po/ca.po, simple-system-monitor@ariel/files/simple-system-monitor@ariel/po/da.po, simple-system-monitor@ariel/files/simple-system-monitor@ariel/po/de.po, simple-system-monitor@ariel/files/simple-system-monitor@ariel/po/es.po, simple-system-monitor@ariel/files/simple-system-monitor@ariel/po/hu.po, simple-system-monitor@ariel/files/simple-system-monitor@ariel/po/it.po, simple-system-monitor@ariel/files/simple-system-monitor@ariel/po/pt_BR.po, simple-system-monitor@ariel/files/simple-system-monitor@ariel/po/ro.po, simple-system-monitor@ariel/files/simple-system-monitor@ariel/po/simple-system-monitor@ariel.pot, simple-system-monitor@ariel/files/simple-system-monitor@ariel/po/sk.po, simple-system-monitor@ariel/files/simple-system-monitor@ariel/po/sv.po, simple-system-monitor@ariel/files/simple-system-monitor@ariel/po/tr.po, simple-system-monitor@ariel/files/simple-system-monitor@ariel/po/zh_CN.po
=> simple-system-monitor@ariel: Update translation files

system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/desklet.js
Attempts to resolve #913
@rcassani If you want to test this, it should at least remove the warning from the Desklets UI.
=> system-monitor-graph@rcassani: Remove unsafe calls and desklet warning

growattmonitor@jtoberling/files/growattmonitor@jtoberling/desklet.js
Could not fully test.
To test with soup 3, edit /usr/share/cinnamon/js/ui/environment.js and change the soup version from 2.4 to 3.0. Save and restart cinnamon.
@jtoberling
=> growattmonitor@jtoberling: Add soup 3 compatibility.

eKreta@thegergo02/files/eKreta@thegergo02/desklet.js
Successful authentication untested. To test with soup 3,
Edit /usr/share/cinnamon/js/ui/environment.js and change the soup version from 2.4 to 3.0. Save and restart cinnamon.
@thegergo02
=> eKreta@thegergo02: soup 3 compatibility.

diskspace@schorschii/files/diskspace@schorschii/desklet.js, diskspace@schorschii/files/diskspace@schorschii/metadata.json
- corrects the usage of async subprocess for RAM monitoring
- use Gio's `query_filesystem_info_async` function for getting filesystem space information instead of spawning a `df` subprocess
closes #932
=> diskspace@schoprschii: Fix Stuttering

diskspace@schorschii/files/diskspace@schorschii/desklet.js, diskspace@schorschii/files/diskspace@schorschii/metadata.json
Same thing as #937 and #938 , now for the RAM monitoring feature. Replaced the `free --bytes` subprocess with async file read of `/proc/meminfo`.
=> diskspace@schorschii: fix stuttering for RAM monitoring

battery@schorschii/files/battery@schorschii/desklet.js, battery@schorschii/files/battery@schorschii/metadata.json
Fixed the text when global UI scale is set to 200%.
=> battery@schorschii: fix text on hi-res screens

yfquotes@thegli/files/yfquotes@thegli/po/da.po
Fixes #1002 
cc @Alan01 @claudiux
=> yfquotes@thegli: Update Danish translation

bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/po/it.po, clock@schorschii/files/clock@schorschii/po/it.po, commandResult@ZimiZones/files/commandResult@ZimiZones/po/it.po, diskspace@schorschii/files/diskspace@schorschii/po/it.po, dual-datetime@rcalixte/files/dual-datetime@rcalixte/po/it.po, netusage@30yavash.com/files/netusage@30yavash.com/po/it.po, notes@schorschii/files/notes@schorschii/po/it.po, show-remote-ip-desklet@nejdetckenobi/files/show-remote-ip-desklet@nejdetckenobi/po/it.po, simple-system-monitor@ariel/files/simple-system-monitor@ariel/po/it.po, system-monitor-graph@rcassani/files/system-monitor-graph@rcassani/po/it.po, temperature@swalladge/files/temperature@swalladge/po/it.po, timelet@linuxedo.com/files/timelet@linuxedo.com/po/it.po, yfquotes@thegli/files/yfquotes@thegli/po/it.po
Hi,
I've reviewed and updated/created some of the Italian translations for various desklets.
Have a nice day :)
=> Adds/Updates Italian translations for various desklets

hostcheck@schorschii/files/hostcheck@schorschii/desklet.js, hostcheck@schorschii/files/hostcheck@schorschii/metadata.json, hostcheck@schorschii/files/hostcheck@schorschii/po/ca.po, hostcheck@schorschii/files/hostcheck@schorschii/po/cs.po, hostcheck@schorschii/files/hostcheck@schorschii/po/da.po, hostcheck@schorschii/files/hostcheck@schorschii/po/de.po, hostcheck@schorschii/files/hostcheck@schorschii/po/es.po, hostcheck@schorschii/files/hostcheck@schorschii/po/hostcheck@schorschii.pot, hostcheck@schorschii/files/hostcheck@schorschii/po/hu.po, hostcheck@schorschii/files/hostcheck@schorschii/po/it.po, hostcheck@schorschii/files/hostcheck@schorschii/po/pt_BR.po, hostcheck@schorschii/files/hostcheck@schorschii/po/ro.po, hostcheck@schorschii/files/hostcheck@schorschii/po/ru.po, hostcheck@schorschii/files/hostcheck@schorschii/po/sv.po, hostcheck@schorschii/files/hostcheck@schorschii/po/tr.po, hostcheck@schorschii/files/hostcheck@schorschii/settings-schema.json
- now uses the Soup lib for HTTP checks to avoid stuttering when starting a curl subprocess
- option to define HTTP success status code (default 200)
- improved translations
fix #1025
=> hostcheck@schorschii: avoid stuttering

hostcheck@schorschii/files/hostcheck@schorschii/desklet.js, hostcheck@schorschii/files/hostcheck@schorschii/metadata.json
=> hostcheck@schorschii: adjustments for Soup3.0 used in Mint21.3

netusage@30yavash.com/files/netusage@30yavash.com/4.0/desklet.js
replace depreciated Clutter.Texture
fixes: #945
=> [netusage@30yavash.com] Bugfix

hostcheck@schorschii/files/hostcheck@schorschii/desklet.js, hostcheck@schorschii/files/hostcheck@schorschii/metadata.json
New way of subprocess initialization with specific flags removes stuttering, see https://github.com/linuxmint/cinnamon-spices-desklets/issues/1025#issuecomment-1898919644.
=> hostcheck@schorschii: subprocess improvement

cinnamon-spices-makepot
New features:
* Automatic updating of translations when the template is updated
* Updated header format
* Add translation support for Glade files and shell scripts
=> Rewrite cinnamon-spices-makepot:

hostcheck@schorschii/files/hostcheck@schorschii/desklet.js, hostcheck@schorschii/files/hostcheck@schorschii/metadata.json
=> hostcheck@schorschii: fix ping zombie processes

hostcheck@schorschii/files/hostcheck@schorschii/desklet.js, hostcheck@schorschii/files/hostcheck@schorschii/metadata.json
closes #1083 
(see also #1033)
=> hostcheck@schorschii: more Soup3 compatibility

calendar@deeppradhan/files/calendar@deeppradhan/desklet.js, calendar@deeppradhan/files/calendar@deeppradhan/metadata.json, calendar@deeppradhan/files/calendar@deeppradhan/po/ca.po, calendar@deeppradhan/files/calendar@deeppradhan/po/calendar@deeppradhan.pot, calendar@deeppradhan/files/calendar@deeppradhan/po/da.po, calendar@deeppradhan/files/calendar@deeppradhan/po/de.po, calendar@deeppradhan/files/calendar@deeppradhan/po/es.po, calendar@deeppradhan/files/calendar@deeppradhan/po/hu.po, calendar@deeppradhan/files/calendar@deeppradhan/po/it.po, calendar@deeppradhan/files/calendar@deeppradhan/po/pt_BR.po, calendar@deeppradhan/files/calendar@deeppradhan/po/ro.po, calendar@deeppradhan/files/calendar@deeppradhan/po/ru.po, calendar@deeppradhan/files/calendar@deeppradhan/po/sk.po, calendar@deeppradhan/files/calendar@deeppradhan/po/sv.po
=> calendar@deeppradhan: Fix translation support

calendar@deeppradhan/files/calendar@deeppradhan/po/fr.po
=> calendar@deeppradhan: Add French translation

calendar@deeppradhan/CHANGELOG.md, calendar@deeppradhan/files/calendar@deeppradhan/desklet.js, calendar@deeppradhan/files/calendar@deeppradhan/metadata.json, calendar@deeppradhan/files/calendar@deeppradhan/po/ca.po, calendar@deeppradhan/files/calendar@deeppradhan/po/calendar@deeppradhan.pot, calendar@deeppradhan/files/calendar@deeppradhan/po/da.po, calendar@deeppradhan/files/calendar@deeppradhan/po/de.po, calendar@deeppradhan/files/calendar@deeppradhan/po/es.po, calendar@deeppradhan/files/calendar@deeppradhan/po/fr.po, calendar@deeppradhan/files/calendar@deeppradhan/po/hu.po, calendar@deeppradhan/files/calendar@deeppradhan/po/it.po, calendar@deeppradhan/files/calendar@deeppradhan/po/pt_BR.po, calendar@deeppradhan/files/calendar@deeppradhan/po/ro.po, calendar@deeppradhan/files/calendar@deeppradhan/po/ru.po, calendar@deeppradhan/files/calendar@deeppradhan/po/sk.po, calendar@deeppradhan/files/calendar@deeppradhan/po/sv.po, calendar@deeppradhan/files/calendar@deeppradhan/settings-schema.json
* Added an option for selecting the first day of the week (Sunday/Monday)
* Added an option for whether to use 24h time format
* Added a CHANGELOG
Closes #295
Closes #1096
=> calendar@deeppradhan: Version 1.2

bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/po/de.po
=> weather@mockturtl: update de.po

hostcheck@schorschii/files/hostcheck@schorschii/po/ca.po, hostcheck@schorschii/files/hostcheck@schorschii/po/hostcheck@schorschii.pot
Updated Catalan translation of @schorschii 's desklet
=> hostcheck@schorschii: updated POT file and Catalan translation

SevenSegmentClock@lxs242/files/SevenSegmentClock@lxs242/po/SevenSegmentClock@lxs242.pot, SevenSegmentClock@lxs242/files/SevenSegmentClock@lxs242/po/ca.po
Updated Catalan translation of @lxs242 's desklet
=>  SevenSegmentClock@lxs242: updated Catalan translation

calculator@scollins/files/calculator@scollins/po/ca.po, calculator@scollins/files/calculator@scollins/po/calculator@scollins.pot
Updated Catalan translation of @collinss 's desklet
=> calculator@scollins: updated Catalan translation

calc@ptandler/files/calc@ptandler/po/ca.po
Created Catalan translation of @ptandler 's desklet
=> calc@ptandler: created Catalan translation

NumericBinaryClock@ozymandiaslone/files/NumericBinaryClock@ozymandiaslone/po/ca.po
Created Catalan translation of the @ozymandiaslone 's desklet
=> NumericBinaryClock@ozymandiaslone: updated POT and created Catalan translation

clocket@tirtha/files/clocket@tirtha/po/ca.po
Created Catalan translation of @tirtharajsinha 's desklet
=> clocket@tirtha: updated POT file and created Catalan translation

diskspace@schorschii/files/diskspace@schorschii/po/ca.po, diskspace@schorschii/files/diskspace@schorschii/po/diskspace@schorschii.pot
Updated Catalan translation of @schorschii 's desklet
=> diskspace@schorschii: updated Catalan translation

clocket@tirtha/files/clocket@tirtha/po/clocket@tirtha.pot, clocket@tirtha/files/clocket@tirtha/settings-schema.json
=> clocket@tirtha: fixes the problem with a duplicated string

dual-datetime@rcalixte/files/dual-datetime@rcalixte/po/ca.po
Created Catalan translation of @rcalixte 's desklet
=> dual-datetime@rcalixte: created Catalan translation

kdecdesklet@joejoetv/files/kdecdesklet@joejoetv/po/ca.po
Created Catalan translation of @JoeJoeTV 's desklet
=> kdecdesklet@joejoetv: created Catalan translation

clocket@tirtha/files/clocket@tirtha/po/ca.po
Update the Catalan translation of @tirtharajsinha 's desklet
=> clocket@tirtha: updated Catalan translation

xkcd@rjanja/files/xkcd@rjanja/po/ca.po
Created Catalan translation of @rjanja 's desklet
=> xkcd@rjanja: created Catalan translation

shutdown@phpdreamer/files/shutdown@phpdreamer/po/ca.po
Created Catalan translation of @phpdreamer's translation
=> shutdown@phpdreamer: updated POT file and created Catalan translation

timelet@linuxedo.com/files/timelet@linuxedo.com/po/ca.po, timelet@linuxedo.com/files/timelet@linuxedo.com/po/timelet@linuxedo.com.pot
Updated Catalan translation of @slgobinath 's desklet
=> timelet@linuxedo.com: updated POT file and Catalan translation

yarr@jtoberling/files/yarr@jtoberling/po/ca.po
Created Catalan translation of @jtoberling 's desklet
=> yarr@jtoberling: updated POT file and created Catalan translation

soundBox@scollins/files/soundBox@scollins/po/ca.po
Created Catalan translation of @collinss 's desklet
=> soundBox@scollins: updated POT file and created Catalan translation

mintoo@sujitagarwal/files/mintoo@sujitagarwal/po/ca.po
Created Catalan translation of @sujitagarwal 's desklet
=> mintoo@sujitagarwal: Updated POT file and created Catalan translation

temperature@india/files/temperature@india/po/ca.po
Created Catalan translation of @india 's desklet
=> temperature@india: updated POT file and created Catalan translation

netusage@30yavash.com/files/netusage@30yavash.com/po/ca.po
Created Catalan translation of @30yavash.com 's desklet (now @pdcurtis is in charge of it)
=> netusage@30yavash.com: updated POT file and created Catalan translation

cryptocoins@pbojan/files/cryptocoins@pbojan/po/ca.po
Created Catalan translation of @pbojan 's desklet
=> cryptocoins@pbojan: updated POT file and created Catalan translation

cpuload@kimse/files/cpuload@kimse/desklet.js, cpuload@kimse/files/cpuload@kimse/metadata.json
=> cpuload@kimse: Fix NaN% on startup

soundBox@scollins/files/soundBox@scollins/soundbox.js
=> soundBox@scollins: Fix missing album artworks in Soundbox desklet using ibclutter v.1.12 or higher

yarr@jtoberling/CHANGELOG.md, yarr@jtoberling/files/yarr@jtoberling/desklet.js, yarr@jtoberling/files/yarr@jtoberling/metadata.json, yarr@jtoberling/files/yarr@jtoberling/po/ca.po, yarr@jtoberling/files/yarr@jtoberling/po/es.po, yarr@jtoberling/files/yarr@jtoberling/po/hu.po, yarr@jtoberling/files/yarr@jtoberling/po/nl.po, yarr@jtoberling/files/yarr@jtoberling/po/yarr@jtoberling.pot
Yarr: ## [1.2.2] - 2024-06-28
- Enhanced logging of AI errors
- Remove tooltips from 1st buttons to improve efficiency
=> yarr 1.2.2 Enhancements

yfquotes@thegli/README.md, yfquotes@thegli/files/yfquotes@thegli/desklet.js, yfquotes@thegli/files/yfquotes@thegli/metadata.json, yfquotes@thegli/files/yfquotes@thegli/po/da.po, yfquotes@thegli/files/yfquotes@thegli/po/de.po, yfquotes@thegli/files/yfquotes@thegli/po/es.po, yfquotes@thegli/files/yfquotes@thegli/po/fi.po, yfquotes@thegli/files/yfquotes@thegli/po/hu.po, yfquotes@thegli/files/yfquotes@thegli/po/it.po, yfquotes@thegli/files/yfquotes@thegli/po/ko.po, yfquotes@thegli/files/yfquotes@thegli/po/nl.po, yfquotes@thegli/files/yfquotes@thegli/po/pt_BR.po, yfquotes@thegli/files/yfquotes@thegli/po/ro.po, yfquotes@thegli/files/yfquotes@thegli/po/ru.po, yfquotes@thegli/files/yfquotes@thegli/po/yfquotes@thegli.pot, yfquotes@thegli/files/yfquotes@thegli/settings-schema.json
- fix minor bug
- improve manual update setting description
=> yfquotes@thegli: add setting to customize background color

xkcd@rjanja/files/xkcd@rjanja/desklet.js
Think this would be pretty neat (^_^)
@rjanja
=> xkcd@rjanja : Random xkcd feature

soundBox@scollins/info.json
=> soundBox@scollins: Update maintainer

ViennaTextBasedWeather@f-istvan/files/ViennaTextBasedWeather@f-istvan/po/ca.po, bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/po/ca.po, deskNote@BrainAxe/files/deskNote@BrainAxe/po/ca.po, devTools@scollins/files/devTools@scollins/po/ca.po, eKreta@thegergo02/files/eKreta@thegergo02/po/ca.po, growattmonitor@jtoberling/files/growattmonitor@jtoberling/po/ca.po, jalalidesklet@30yavash.com/files/jalalidesklet@30yavash.com/po/ca.po, jira@codeunifier/files/jira@codeunifier/po/ca.po, nepalipatro@deeppradhan/files/nepalipatro@deeppradhan/po/ca.po, panchang@india/files/panchang@india/po/ca.po, reddit-reader@orangeshark/files/reddit-reader@orangeshark/po/ca.po, top@ryannerd/files/top@ryannerd/po/ca.po, yarr@jtoberling/files/yarr@jtoberling/po/ca.po, yfquotes@thegli/files/yfquotes@thegli/po/ca.po
* bbcwx@oak-wood.co.uk
* deskNote@BrainAxe
* devTools@scollins
* eKreta@thegergo02
* growattmonitor@jtoberling
* jalalidesklet@30yavash.com
* jira@codeunifier
* nepalipatro@deeppradhan
* panchang@india
* reddit-reader@orangeshark
* top@ryannerd
* ViennaTextBasedWeather@f-istvan
* yarr@jtoberling
* yfquotes@thegli
=> Add Catalan translations

deskNote@BrainAxe/files/deskNote@BrainAxe/po/ca.po, temperature@swalladge/files/temperature@swalladge/po/ca.po
* deskNote@BrainAxe
* temperature@swalladge
=> Update Catalan translations

vaktija-desklet@MuxBH28/README.md, vaktija-desklet@MuxBH28/files/vaktija-desklet@MuxBH28/desklet.js, vaktija-desklet@MuxBH28/files/vaktija-desklet@MuxBH28/metadata.json, vaktija-desklet@MuxBH28/files/vaktija-desklet@MuxBH28/po/vaktija-desklet@MuxBH28.pot, vaktija-desklet@MuxBH28/files/vaktija-desklet@MuxBH28/settings-schema.json
* Added language chooser in settings
=> vaktija-desklet@MuxBH28: Version 1.3

yfquotes@thegli/CHANGELOG.md, yfquotes@thegli/files/yfquotes@thegli/desklet.js, yfquotes@thegli/files/yfquotes@thegli/metadata.json, yfquotes@thegli/files/yfquotes@thegli/po/ca.po, yfquotes@thegli/files/yfquotes@thegli/po/da.po, yfquotes@thegli/files/yfquotes@thegli/po/de.po, yfquotes@thegli/files/yfquotes@thegli/po/es.po, yfquotes@thegli/files/yfquotes@thegli/po/fi.po, yfquotes@thegli/files/yfquotes@thegli/po/hu.po, yfquotes@thegli/files/yfquotes@thegli/po/it.po, yfquotes@thegli/files/yfquotes@thegli/po/ko.po, yfquotes@thegli/files/yfquotes@thegli/po/nl.po, yfquotes@thegli/files/yfquotes@thegli/po/pt_BR.po, yfquotes@thegli/files/yfquotes@thegli/po/ro.po, yfquotes@thegli/files/yfquotes@thegli/po/ru.po, yfquotes@thegli/files/yfquotes@thegli/po/yfquotes@thegli.pot
- cache quotes responses for each desklet instance separately
- restore automatic quotes data refresh on settings import
=> yfquotes@thegli: restore auto-refresh on import

InternetTimeDesklet@stefan/files/InternetTimeDesklet@stefan/po/de.po
Reposting this because I accidentially added another commit to the old PR.
=> InternetTimeDesklet@stefan: Added German translation

notes@schorschii/files/notes@schorschii/po/ca.po, notes@schorschii/files/notes@schorschii/po/da.po, notes@schorschii/files/notes@schorschii/po/de.po, notes@schorschii/files/notes@schorschii/po/fr.po, notes@schorschii/files/notes@schorschii/po/hu.po, notes@schorschii/files/notes@schorschii/po/it.po, notes@schorschii/files/notes@schorschii/po/nl.po, notes@schorschii/files/notes@schorschii/po/pt.po, notes@schorschii/files/notes@schorschii/po/pt_BR.po, notes@schorschii/files/notes@schorschii/po/ro.po, notes@schorschii/files/notes@schorschii/po/ru.po, notes@schorschii/files/notes@schorschii/po/sv.po, notes@schorschii/files/notes@schorschii/po/tr.po
- removed the 'fuzzy' flag which prevents translations from being displayed
- fixed wrong translations introduced with #1293
=> notes@schorschii: update/fix translations

analog-clock@cobinja.de/files/analog-clock@cobinja.de/po/fi.po, bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/po/fi.po, calendar@deeppradhan/files/calendar@deeppradhan/po/fi.po, calendar@schorschii/files/calendar@schorschii/po/fi.po, clock@schorschii/files/clock@schorschii/po/fi.po, clocket@tirtha/files/clocket@tirtha/po/fi.po, commandOfTheDay@logg/files/commandOfTheDay@logg/po/fi.po, commandResult@ZimiZones/files/commandResult@ZimiZones/po/fi.po
New language packs for Finnish
=> Desklets finnish translations

cpuload@kimse/files/cpuload@kimse/po/fi.po, deskNote@BrainAxe/files/deskNote@BrainAxe/po/fi.po, diskspace@schorschii/files/diskspace@schorschii/po/fi.po, dual-datetime@rcalixte/files/dual-datetime@rcalixte/po/fi.po, kdecdesklet@joejoetv/files/kdecdesklet@joejoetv/po/fi.po, notes@schorschii/files/notes@schorschii/po/fi.po
New tested language packages in Finnish
=> Finnish language packages

timelet@linuxedo.com/files/timelet@linuxedo.com/po/fi.po, yarr@jtoberling/files/yarr@jtoberling/po/ca.po, yarr@jtoberling/files/yarr@jtoberling/po/es.po, yarr@jtoberling/files/yarr@jtoberling/po/fi.po, yarr@jtoberling/files/yarr@jtoberling/po/hu.po, yarr@jtoberling/files/yarr@jtoberling/po/nl.po, yarr@jtoberling/files/yarr@jtoberling/po/yarr@jtoberling.pot, yfquotes@thegli/files/yfquotes@thegli/po/fi.po
New Finnish language packs and one update.
One update to the pot file. I updated it as instructed by makepot. Tested using eng base pot in Finnish translation.
=> Finnish language package

yfquotes@thegli/CHANGELOG.md, yfquotes@thegli/README.md, yfquotes@thegli/files/yfquotes@thegli/desklet.js, yfquotes@thegli/files/yfquotes@thegli/metadata.json, yfquotes@thegli/files/yfquotes@thegli/po/ca.po, yfquotes@thegli/files/yfquotes@thegli/po/da.po, yfquotes@thegli/files/yfquotes@thegli/po/de.po, yfquotes@thegli/files/yfquotes@thegli/po/es.po, yfquotes@thegli/files/yfquotes@thegli/po/fi.po, yfquotes@thegli/files/yfquotes@thegli/po/hu.po, yfquotes@thegli/files/yfquotes@thegli/po/it.po, yfquotes@thegli/files/yfquotes@thegli/po/ko.po, yfquotes@thegli/files/yfquotes@thegli/po/nl.po, yfquotes@thegli/files/yfquotes@thegli/po/pt_BR.po, yfquotes@thegli/files/yfquotes@thegli/po/ro.po, yfquotes@thegli/files/yfquotes@thegli/po/ru.po, yfquotes@thegli/files/yfquotes@thegli/po/yfquotes@thegli.pot, yfquotes@thegli/files/yfquotes@thegli/settings-schema.json
- detect and replace expired authorization parameters (fixes #1315)
- correct documentation for automatic refresh after import
- update DOW 30 component symbols
=> yfquotes@thegli: auto-refresh expired auth parameters

test-spice
* Update validate_spice to return true/false whether spice is valid
* Add reload_xlet to tell Cinnamon to reload the devtest applet after successful copy
cc @timfeierabend
=> Add reload after successful copy

daysCountdown@KopfDesDaemons/files/daysCountdown@KopfDesDaemons/metadata.json
Closes #1326
cc @KopfdesDaemons
=> daysCountdown@KopfDesDaemons: Remove hard-coded maximum value

yfquotes@thegli/files/yfquotes@thegli/po/ca.po, yfquotes@thegli/files/yfquotes@thegli/po/yfquotes@thegli.pot
Updated Catalan translation for @thegli 's spice desklet
=> yfquotes@thegli: complete + minor fixes for Catalan translation

systemUptime@KopfDesDaemons/files/systemUptime@KopfDesDaemons/po/ca.po
Created Catalan trasnlation for @KopfdesDaemons 's spice desklet
=> systemUptime@KopfDesDaemons: add Catalan translation

daysCountdown@KopfDesDaemons/files/daysCountdown@KopfDesDaemons/po/ca.po
Created Catalan translation for @KopfdesDaemons 's spice desklet
=> daysCountdown@KopfDesDaemons: add Catalan translation

adventCandles@KopfdesDaemons/files/adventCandles@KopfdesDaemons/po/ca.po
Created Catalan translation for @KopfdesDaemons spice desklet
=> adventCandles@KopfdesDaemons: add Catalan translation

yfquotes@thegli/CHANGELOG.md, yfquotes@thegli/files/yfquotes@thegli/desklet.js, yfquotes@thegli/files/yfquotes@thegli/metadata.json, yfquotes@thegli/files/yfquotes@thegli/po/yfquotes@thegli.pot
include required quote fields in url parameters
=> yfquotes@thegli: restore absent quote details

daysCountdown@KopfDesDaemons/files/daysCountdown@KopfDesDaemons/po/fi.po
=> Fixed tranlater

TimeAndDate@nightflame/files/TimeAndDate@nightflame/po/fi.po, eKreta@thegergo02/files/eKreta@thegergo02/po/fi.po
Translater to finnish languages.
=> Translater to finnish

TimeAndDate@nightflame/files/TimeAndDate@nightflame/po/fi.po, eKreta@thegergo02/files/eKreta@thegergo02/po/fi.po, kdecdesklet@joejoetv/files/kdecdesklet@joejoetv/po/fi.po
Corrected a few spelling errors in Finnish.
=> Fixed translater

yfquotes@thegli/CHANGELOG.md, yfquotes@thegli/files/yfquotes@thegli/desklet.js, yfquotes@thegli/files/yfquotes@thegli/metadata.json, yfquotes@thegli/files/yfquotes@thegli/po/ca.po, yfquotes@thegli/files/yfquotes@thegli/po/da.po, yfquotes@thegli/files/yfquotes@thegli/po/de.po, yfquotes@thegli/files/yfquotes@thegli/po/es.po, yfquotes@thegli/files/yfquotes@thegli/po/fi.po, yfquotes@thegli/files/yfquotes@thegli/po/hu.po, yfquotes@thegli/files/yfquotes@thegli/po/it.po, yfquotes@thegli/files/yfquotes@thegli/po/ko.po, yfquotes@thegli/files/yfquotes@thegli/po/nl.po, yfquotes@thegli/files/yfquotes@thegli/po/pt_BR.po, yfquotes@thegli/files/yfquotes@thegli/po/ro.po, yfquotes@thegli/files/yfquotes@thegli/po/ru.po, yfquotes@thegli/files/yfquotes@thegli/po/yfquotes@thegli.pot
=> yfquotes@thegli: fix infinite loop on empty quotes list

AlbumArt3.0@claudiux/files/AlbumArt3.0@claudiux/po/ca.po, calendar@bahrampc/files/calendar@bahrampc/po/ca.po, vaktija-desklet@MuxBH28/files/vaktija-desklet@MuxBH28/po/ca.po, yarr@jtoberling/files/yarr@jtoberling/po/ca.po
* AlbumArt3.0@claudiux: Add Catalan translation
* calendar@bahrampc: Add Catalan translation
* vaktija-desklet@MuxBH28: Add Catalan translation
* yarr@jtoberling: Update Catalan translation
=> Add/Update Catalan translations

moonlight-clock@torchipeppo/README.md, moonlight-clock@torchipeppo/files/moonlight-clock@torchipeppo/metadata.json
This should make the screenshots visible on the Cinnamon Spices website as well.
Couldn't do this until after the initial release.
=> [moonlight-clock@torchipeppo] Update README for Spices website

xkcd@rjanja/files/xkcd@rjanja/desklet.js, xkcd@rjanja/files/xkcd@rjanja/stylesheet.css
As the alt text is quite important to the XKCD comics i added the text under the image.
=> added XKCD alt text under the image

xkcd@rjanja/files/xkcd@rjanja/desklet.js, xkcd@rjanja/files/xkcd@rjanja/stylesheet.css
Reverts linuxmint/cinnamon-spices-desklets#1421
=> Revert "xkcd@rjanja: Add XKCD alt text under the image

yfquotes@thegli/CHANGELOG.md, yfquotes@thegli/files/yfquotes@thegli/desklet.js, yfquotes@thegli/files/yfquotes@thegli/metadata.json, yfquotes@thegli/files/yfquotes@thegli/po/ca.po, yfquotes@thegli/files/yfquotes@thegli/po/da.po, yfquotes@thegli/files/yfquotes@thegli/po/de.po, yfquotes@thegli/files/yfquotes@thegli/po/es.po, yfquotes@thegli/files/yfquotes@thegli/po/fi.po, yfquotes@thegli/files/yfquotes@thegli/po/hu.po, yfquotes@thegli/files/yfquotes@thegli/po/it.po, yfquotes@thegli/files/yfquotes@thegli/po/ko.po, yfquotes@thegli/files/yfquotes@thegli/po/nl.po, yfquotes@thegli/files/yfquotes@thegli/po/pt_BR.po, yfquotes@thegli/files/yfquotes@thegli/po/ro.po, yfquotes@thegli/files/yfquotes@thegli/po/ru.po, yfquotes@thegli/files/yfquotes@thegli/po/yfquotes@thegli.pot
- fix "TypeError: responseResult is null"
- stringify error response for display and logging
- replace Mainloop with GLib for timer functionality
=> yfquotes@thegli: handle null response, improve error display

moonlight-clock@torchipeppo/TRANSLATORS.md, moonlight-clock@torchipeppo/files/moonlight-clock@torchipeppo/po/it.po, moonlight-clock@torchipeppo/files/moonlight-clock@torchipeppo/po/moonlight-clock@torchipeppo.pot
This should have been released since the beginning, but it appears I missed it until a few days ago. Anyway, here it is. (And I actually validated the file's position this time. Apologies for before: I had expected this to be an inconsequential update.)
=> [moonlight-clock@torchipeppo] Add TRANSLATORS.md

systemUptime@KopfDesDaemons/files/systemUptime@KopfDesDaemons/desklet.js
I counted pixels at two different font sizes and made a model of the unaccounted for padding pixels
=> systemUptime@KopfDesDaemons: Fix squished image bug

notes@schorschii/files/notes@schorschii/desklet.js, notes@schorschii/files/notes@schorschii/metadata.json, notes@schorschii/files/notes@schorschii/po/de.po, notes@schorschii/files/notes@schorschii/po/notes@schorschii.pot, notes@schorschii/files/notes@schorschii/settings-schema.json
=> notes@schorschii: add text shdaow option

ganjine@mohammad-sn/files/ganjine@mohammad-sn/desklet.js
@mohammad-sn 
This fixes the zwnj rendering issue.
=> Ganjineh:  fix issue #1453 - replace zwnj code with the correct one

ganjine@mohammad-sn/files/ganjine@mohammad-sn/desklet.js
@mohammad-sn 
It is a more complete fix to include all unicode characters rendering.
I have also moved the replace command down to include poet name (just in case).
=> Fix issue 1456

yfquotes@thegli/CHANGELOG.md, yfquotes@thegli/README.md, yfquotes@thegli/files/yfquotes@thegli/desklet.js, yfquotes@thegli/files/yfquotes@thegli/metadata.json, yfquotes@thegli/files/yfquotes@thegli/po/ca.po, yfquotes@thegli/files/yfquotes@thegli/po/da.po, yfquotes@thegli/files/yfquotes@thegli/po/de.po, yfquotes@thegli/files/yfquotes@thegli/po/es.po, yfquotes@thegli/files/yfquotes@thegli/po/fi.po, yfquotes@thegli/files/yfquotes@thegli/po/hu.po, yfquotes@thegli/files/yfquotes@thegli/po/it.po, yfquotes@thegli/files/yfquotes@thegli/po/ko.po, yfquotes@thegli/files/yfquotes@thegli/po/nl.po, yfquotes@thegli/files/yfquotes@thegli/po/pt_BR.po, yfquotes@thegli/files/yfquotes@thegli/po/ro.po, yfquotes@thegli/files/yfquotes@thegli/po/ru.po, yfquotes@thegli/files/yfquotes@thegli/po/yfquotes@thegli.pot, yfquotes@thegli/files/yfquotes@thegli/settings-schema.json
=> yfquotes@thegli: integrate curl to deal with latest YF changes

bbcwx@oak-wood.co.uk/files/bbcwx@oak-wood.co.uk/po/it.po, quicklinks@NotSirius-A/files/quicklinks@NotSirius-A/po/it.po, yfquotes@thegli/files/yfquotes@thegli/po/it.po
With this PR we're at 100% in Italian translations :D
=> Updates missing Italian translations

ganjine@mohammad-sn/files/ganjine@mohammad-sn/desklet.js, ganjine@mohammad-sn/files/ganjine@mohammad-sn/settings-schema.json
Hey Mohammad,
I'm not sure if these changes are enough to get the job done as expected, since I'm a total newbie in JS and Cinnamon Spices. 
But it seems to work anyway.
@mohammad-sn
=> ganjine@mohammad-sn: Adding history size limit.
